// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.5
// source: discovery.proto

package discoveryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RendezvousService_RegisterHost_FullMethodName   = "/discovery.v1.RendezvousService/RegisterHost"
	RendezvousService_Heartbeat_FullMethodName      = "/discovery.v1.RendezvousService/Heartbeat"
	RendezvousService_DeregisterHost_FullMethodName = "/discovery.v1.RendezvousService/DeregisterHost"
	RendezvousService_ListHosts_FullMethodName      = "/discovery.v1.RendezvousService/ListHosts"
	RendezvousService_GetHost_FullMethodName        = "/discovery.v1.RendezvousService/GetHost"
	RendezvousService_WatchHosts_FullMethodName     = "/discovery.v1.RendezvousService/WatchHosts"
	RendezvousService_Health_FullMethodName         = "/discovery.v1.RendezvousService/Health"
)

// RendezvousServiceClient is the client API for RendezvousService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RendezvousService manages host discovery across LAN and WAN
type RendezvousServiceClient interface {
	RegisterHost(ctx context.Context, in *RendezvousHost, opts ...grpc.CallOption) (*RegisterHostResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	DeregisterHost(ctx context.Context, in *DeregisterHostRequest, opts ...grpc.CallOption) (*Empty, error)
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*RendezvousHost, error)
	WatchHosts(ctx context.Context, in *WatchHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostEvent], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type rendezvousServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRendezvousServiceClient(cc grpc.ClientConnInterface) RendezvousServiceClient {
	return &rendezvousServiceClient{cc}
}

func (c *rendezvousServiceClient) RegisterHost(ctx context.Context, in *RendezvousHost, opts ...grpc.CallOption) (*RegisterHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHostResponse)
	err := c.cc.Invoke(ctx, RendezvousService_RegisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RendezvousService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousServiceClient) DeregisterHost(ctx context.Context, in *DeregisterHostRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RendezvousService_DeregisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousServiceClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, RendezvousService_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousServiceClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*RendezvousHost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RendezvousHost)
	err := c.cc.Invoke(ctx, RendezvousService_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousServiceClient) WatchHosts(ctx context.Context, in *WatchHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RendezvousService_ServiceDesc.Streams[0], RendezvousService_WatchHosts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchHostsRequest, HostEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RendezvousService_WatchHostsClient = grpc.ServerStreamingClient[HostEvent]

func (c *rendezvousServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RendezvousService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RendezvousServiceServer is the server API for RendezvousService service.
// All implementations must embed UnimplementedRendezvousServiceServer
// for forward compatibility.
//
// RendezvousService manages host discovery across LAN and WAN
type RendezvousServiceServer interface {
	RegisterHost(context.Context, *RendezvousHost) (*RegisterHostResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	DeregisterHost(context.Context, *DeregisterHostRequest) (*Empty, error)
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	GetHost(context.Context, *GetHostRequest) (*RendezvousHost, error)
	WatchHosts(*WatchHostsRequest, grpc.ServerStreamingServer[HostEvent]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRendezvousServiceServer()
}

// UnimplementedRendezvousServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRendezvousServiceServer struct{}

func (UnimplementedRendezvousServiceServer) RegisterHost(context.Context, *RendezvousHost) (*RegisterHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHost not implemented")
}
func (UnimplementedRendezvousServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRendezvousServiceServer) DeregisterHost(context.Context, *DeregisterHostRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterHost not implemented")
}
func (UnimplementedRendezvousServiceServer) ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedRendezvousServiceServer) GetHost(context.Context, *GetHostRequest) (*RendezvousHost, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedRendezvousServiceServer) WatchHosts(*WatchHostsRequest, grpc.ServerStreamingServer[HostEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchHosts not implemented")
}
func (UnimplementedRendezvousServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRendezvousServiceServer) mustEmbedUnimplementedRendezvousServiceServer() {}
func (UnimplementedRendezvousServiceServer) testEmbeddedByValue()                           {}

// UnsafeRendezvousServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RendezvousServiceServer will
// result in compilation errors.
type UnsafeRendezvousServiceServer interface {
	mustEmbedUnimplementedRendezvousServiceServer()
}

func RegisterRendezvousServiceServer(s grpc.ServiceRegistrar, srv RendezvousServiceServer) {
	// If the following call panics, it indicates UnimplementedRendezvousServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RendezvousService_ServiceDesc, srv)
}

func _RendezvousService_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RendezvousHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServiceServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendezvousService_RegisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServiceServer).RegisterHost(ctx, req.(*RendezvousHost))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendezvousService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendezvousService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendezvousService_DeregisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServiceServer).DeregisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendezvousService_DeregisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServiceServer).DeregisterHost(ctx, req.(*DeregisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendezvousService_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServiceServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendezvousService_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServiceServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendezvousService_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServiceServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendezvousService_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServiceServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendezvousService_WatchHosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchHostsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RendezvousServiceServer).WatchHosts(m, &grpc.GenericServerStream[WatchHostsRequest, HostEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RendezvousService_WatchHostsServer = grpc.ServerStreamingServer[HostEvent]

func _RendezvousService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendezvousService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RendezvousService_ServiceDesc is the grpc.ServiceDesc for RendezvousService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RendezvousService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.v1.RendezvousService",
	HandlerType: (*RendezvousServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHost",
			Handler:    _RendezvousService_RegisterHost_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _RendezvousService_Heartbeat_Handler,
		},
		{
			MethodName: "DeregisterHost",
			Handler:    _RendezvousService_DeregisterHost_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _RendezvousService_ListHosts_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _RendezvousService_GetHost_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RendezvousService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHosts",
			Handler:       _RendezvousService_WatchHosts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "discovery.proto",
}
