// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: discovery.proto

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RendezvousHost struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HostId             string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PublicEndpoint     string                 `protobuf:"bytes,3,opt,name=public_endpoint,json=publicEndpoint,proto3" json:"public_endpoint,omitempty"`
	LocalEndpoint      string                 `protobuf:"bytes,4,opt,name=local_endpoint,json=localEndpoint,proto3" json:"local_endpoint,omitempty"`
	Os                 string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Version            string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Capabilities       *CapabilitiesSnapshot  `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	CertFingerprint    string                 `protobuf:"bytes,9,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	Region             string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	ActiveSessionCount int32                  `protobuf:"varint,11,opt,name=active_session_count,json=activeSessionCount,proto3" json:"active_session_count,omitempty"`
	LastSeenAt         string                 `protobuf:"bytes,12,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	RegisteredAt       string                 `protobuf:"bytes,13,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RendezvousHost) Reset() {
	*x = RendezvousHost{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RendezvousHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RendezvousHost) ProtoMessage() {}

func (x *RendezvousHost) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RendezvousHost.ProtoReflect.Descriptor instead.
func (*RendezvousHost) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *RendezvousHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RendezvousHost) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RendezvousHost) GetPublicEndpoint() string {
	if x != nil {
		return x.PublicEndpoint
	}
	return ""
}

func (x *RendezvousHost) GetLocalEndpoint() string {
	if x != nil {
		return x.LocalEndpoint
	}
	return ""
}

func (x *RendezvousHost) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RendezvousHost) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RendezvousHost) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RendezvousHost) GetCapabilities() *CapabilitiesSnapshot {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RendezvousHost) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *RendezvousHost) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RendezvousHost) GetActiveSessionCount() int32 {
	if x != nil {
		return x.ActiveSessionCount
	}
	return 0
}

func (x *RendezvousHost) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *RendezvousHost) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type CapabilitiesSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gpus           []*GPUCapability       `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Codecs         []string               `protobuf:"bytes,2,rep,name=codecs,proto3" json:"codecs,omitempty"`
	Transports     []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	MaxResolution  *Resolution            `protobuf:"bytes,4,opt,name=max_resolution,json=maxResolution,proto3" json:"max_resolution,omitempty"`
	MaxRefreshRate int32                  `protobuf:"varint,5,opt,name=max_refresh_rate,json=maxRefreshRate,proto3" json:"max_refresh_rate,omitempty"`
	HdrFormats     []string               `protobuf:"bytes,6,rep,name=hdr_formats,json=hdrFormats,proto3" json:"hdr_formats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapabilitiesSnapshot) Reset() {
	*x = CapabilitiesSnapshot{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesSnapshot) ProtoMessage() {}

func (x *CapabilitiesSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesSnapshot.ProtoReflect.Descriptor instead.
func (*CapabilitiesSnapshot) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesSnapshot) GetGpus() []*GPUCapability {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *CapabilitiesSnapshot) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *CapabilitiesSnapshot) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *CapabilitiesSnapshot) GetMaxResolution() *Resolution {
	if x != nil {
		return x.MaxResolution
	}
	return nil
}

func (x *CapabilitiesSnapshot) GetMaxRefreshRate() int32 {
	if x != nil {
		return x.MaxRefreshRate
	}
	return 0
}

func (x *CapabilitiesSnapshot) GetHdrFormats() []string {
	if x != nil {
		return x.HdrFormats
	}
	return nil
}

type GPUCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Encoder       string                 `protobuf:"bytes,4,opt,name=encoder,proto3" json:"encoder,omitempty"`
	Codecs        []string               `protobuf:"bytes,5,rep,name=codecs,proto3" json:"codecs,omitempty"`
	VramGb        int32                  `protobuf:"varint,6,opt,name=vram_gb,json=vramGb,proto3" json:"vram_gb,omitempty"`
	ThermalC      int32                  `protobuf:"varint,7,opt,name=thermal_c,json=thermalC,proto3" json:"thermal_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUCapability) Reset() {
	*x = GPUCapability{}
	mi := &file_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUCapability) ProtoMessage() {}

func (x *GPUCapability) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUCapability.ProtoReflect.Descriptor instead.
func (*GPUCapability) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *GPUCapability) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUCapability) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUCapability) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUCapability) GetEncoder() string {
	if x != nil {
		return x.Encoder
	}
	return ""
}

func (x *GPUCapability) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *GPUCapability) GetVramGb() int32 {
	if x != nil {
		return x.VramGb
	}
	return 0
}

func (x *GPUCapability) GetThermalC() int32 {
	if x != nil {
		return x.ThermalC
	}
	return 0
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *Resolution) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resolution) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type RegisterHostResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LeaseId              string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	HeartbeatIntervalSec int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	ExpiresAt            string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterHostResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RegisterHostResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *RegisterHostResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type HeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HostId             string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	LeaseId            string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ActiveSessionCount int32                  `protobuf:"varint,4,opt,name=active_session_count,json=activeSessionCount,proto3" json:"active_session_count,omitempty"`
	TimestampNs        int64                  `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveSessionCount() int32 {
	if x != nil {
		return x.ActiveSessionCount
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseExtended bool                   `protobuf:"varint,1,opt,name=lease_extended,json=leaseExtended,proto3" json:"lease_extended,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetLeaseExtended() bool {
	if x != nil {
		return x.LeaseExtended
	}
	return false
}

func (x *HeartbeatResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *HeartbeatResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type DeregisterHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterHostRequest) Reset() {
	*x = DeregisterHostRequest{}
	mi := &file_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterHostRequest) ProtoMessage() {}

func (x *DeregisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterHostRequest.ProtoReflect.Descriptor instead.
func (*DeregisterHostRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *DeregisterHostRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *DeregisterHostRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_discovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{8}
}

type ListHostsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Region           string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CapabilityFilter *CapabilityFilter      `protobuf:"bytes,4,opt,name=capability_filter,json=capabilityFilter,proto3" json:"capability_filter,omitempty"`
	PageSize         int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken        string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_discovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{9}
}

func (x *ListHostsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListHostsRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListHostsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListHostsRequest) GetCapabilityFilter() *CapabilityFilter {
	if x != nil {
		return x.CapabilityFilter
	}
	return nil
}

func (x *ListHostsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListHostsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type CapabilityFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuModels     []string               `protobuf:"bytes,1,rep,name=gpu_models,json=gpuModels,proto3" json:"gpu_models,omitempty"`
	Codecs        []string               `protobuf:"bytes,2,rep,name=codecs,proto3" json:"codecs,omitempty"`
	Transports    []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityFilter) Reset() {
	*x = CapabilityFilter{}
	mi := &file_discovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityFilter) ProtoMessage() {}

func (x *CapabilityFilter) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityFilter.ProtoReflect.Descriptor instead.
func (*CapabilityFilter) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{10}
}

func (x *CapabilityFilter) GetGpuModels() []string {
	if x != nil {
		return x.GpuModels
	}
	return nil
}

func (x *CapabilityFilter) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *CapabilityFilter) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*RendezvousHost      `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_discovery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{11}
}

func (x *ListHostsResponse) GetHosts() []*RendezvousHost {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ListHostsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListHostsResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type GetHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostRequest) Reset() {
	*x = GetHostRequest{}
	mi := &file_discovery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostRequest) ProtoMessage() {}

func (x *GetHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostRequest.ProtoReflect.Descriptor instead.
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{12}
}

func (x *GetHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type WatchHostsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Region           string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	CapabilityFilter *CapabilityFilter      `protobuf:"bytes,3,opt,name=capability_filter,json=capabilityFilter,proto3" json:"capability_filter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WatchHostsRequest) Reset() {
	*x = WatchHostsRequest{}
	mi := &file_discovery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchHostsRequest) ProtoMessage() {}

func (x *WatchHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchHostsRequest.ProtoReflect.Descriptor instead.
func (*WatchHostsRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{13}
}

func (x *WatchHostsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WatchHostsRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *WatchHostsRequest) GetCapabilityFilter() *CapabilityFilter {
	if x != nil {
		return x.CapabilityFilter
	}
	return nil
}

type HostEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Host          *RendezvousHost        `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEvent) Reset() {
	*x = HostEvent{}
	mi := &file_discovery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEvent) ProtoMessage() {}

func (x *HostEvent) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEvent.ProtoReflect.Descriptor instead.
func (*HostEvent) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{14}
}

func (x *HostEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HostEvent) GetHost() *RendezvousHost {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *HostEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_discovery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{15}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Checks        []*HealthCheck         `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_discovery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetChecks() []*HealthCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_discovery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\fdiscovery.v1\"\xdc\x03\n" +
	"\x0eRendezvousHost\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12'\n" +
	"\x0fpublic_endpoint\x18\x03 \x01(\tR\x0epublicEndpoint\x12%\n" +
	"\x0elocal_endpoint\x18\x04 \x01(\tR\rlocalEndpoint\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12F\n" +
	"\fcapabilities\x18\b \x01(\v2\".discovery.v1.CapabilitiesSnapshotR\fcapabilities\x12)\n" +
	"\x10cert_fingerprint\x18\t \x01(\tR\x0fcertFingerprint\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x120\n" +
	"\x14active_session_count\x18\v \x01(\x05R\x12activeSessionCount\x12 \n" +
	"\flast_seen_at\x18\f \x01(\tR\n" +
	"lastSeenAt\x12#\n" +
	"\rregistered_at\x18\r \x01(\tR\fregisteredAt\"\x8b\x02\n" +
	"\x14CapabilitiesSnapshot\x12/\n" +
	"\x04gpus\x18\x01 \x03(\v2\x1b.discovery.v1.GPUCapabilityR\x04gpus\x12\x16\n" +
	"\x06codecs\x18\x02 \x03(\tR\x06codecs\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\x12?\n" +
	"\x0emax_resolution\x18\x04 \x01(\v2\x18.discovery.v1.ResolutionR\rmaxResolution\x12(\n" +
	"\x10max_refresh_rate\x18\x05 \x01(\x05R\x0emaxRefreshRate\x12\x1f\n" +
	"\vhdr_formats\x18\x06 \x03(\tR\n" +
	"hdrFormats\"\xbb\x01\n" +
	"\rGPUCapability\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x18\n" +
	"\aencoder\x18\x04 \x01(\tR\aencoder\x12\x16\n" +
	"\x06codecs\x18\x05 \x03(\tR\x06codecs\x12\x17\n" +
	"\avram_gb\x18\x06 \x01(\x05R\x06vramGb\x12\x1b\n" +
	"\tthermal_c\x18\a \x01(\x05R\bthermalC\":\n" +
	"\n" +
	"Resolution\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"\x86\x01\n" +
	"\x14RegisterHostResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x124\n" +
	"\x16heartbeat_interval_sec\x18\x02 \x01(\x05R\x14heartbeatIntervalSec\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\xb3\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x120\n" +
	"\x14active_session_count\x18\x04 \x01(\x05R\x12activeSessionCount\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs\"q\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0elease_extended\x18\x01 \x01(\bR\rleaseExtended\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"c\n" +
	"\x15DeregisterHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\a\n" +
	"\x05Empty\"\xe8\x01\n" +
	"\x10ListHostsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12K\n" +
	"\x11capability_filter\x18\x04 \x01(\v2\x1e.discovery.v1.CapabilityFilterR\x10capabilityFilter\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"i\n" +
	"\x10CapabilityFilter\x12\x1d\n" +
	"\n" +
	"gpu_models\x18\x01 \x03(\tR\tgpuModels\x12\x16\n" +
	"\x06codecs\x18\x02 \x03(\tR\x06codecs\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\"\x8e\x01\n" +
	"\x11ListHostsResponse\x122\n" +
	"\x05hosts\x18\x01 \x03(\v2\x1c.discovery.v1.RendezvousHostR\x05hosts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\")\n" +
	"\x0eGetHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"\x95\x01\n" +
	"\x11WatchHostsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12K\n" +
	"\x11capability_filter\x18\x03 \x01(\v2\x1e.discovery.v1.CapabilityFilterR\x10capabilityFilter\"\x7f\n" +
	"\tHostEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x120\n" +
	"\x04host\x18\x02 \x01(\v2\x1c.discovery.v1.RendezvousHostR\x04host\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"[\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x121\n" +
	"\x06checks\x18\x02 \x03(\v2\x19.discovery.v1.HealthCheckR\x06checks\"Q\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail2\xa3\x04\n" +
	"\x11RendezvousService\x12P\n" +
	"\fRegisterHost\x12\x1c.discovery.v1.RendezvousHost\x1a\".discovery.v1.RegisterHostResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.discovery.v1.HeartbeatRequest\x1a\x1f.discovery.v1.HeartbeatResponse\x12J\n" +
	"\x0eDeregisterHost\x12#.discovery.v1.DeregisterHostRequest\x1a\x13.discovery.v1.Empty\x12L\n" +
	"\tListHosts\x12\x1e.discovery.v1.ListHostsRequest\x1a\x1f.discovery.v1.ListHostsResponse\x12E\n" +
	"\aGetHost\x12\x1c.discovery.v1.GetHostRequest\x1a\x1c.discovery.v1.RendezvousHost\x12H\n" +
	"\n" +
	"WatchHosts\x12\x1f.discovery.v1.WatchHostsRequest\x1a\x17.discovery.v1.HostEvent0\x01\x12C\n" +
	"\x06Health\x12\x1b.discovery.v1.HealthRequest\x1a\x1c.discovery.v1.HealthResponseBCZAgithub.com/HelixDevelopment/HelixPlay/pkg/protocol/v1;discoveryv1b\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_discovery_proto_goTypes = []any{
	(*RendezvousHost)(nil),        // 0: discovery.v1.RendezvousHost
	(*CapabilitiesSnapshot)(nil),  // 1: discovery.v1.CapabilitiesSnapshot
	(*GPUCapability)(nil),         // 2: discovery.v1.GPUCapability
	(*Resolution)(nil),            // 3: discovery.v1.Resolution
	(*RegisterHostResponse)(nil),  // 4: discovery.v1.RegisterHostResponse
	(*HeartbeatRequest)(nil),      // 5: discovery.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: discovery.v1.HeartbeatResponse
	(*DeregisterHostRequest)(nil), // 7: discovery.v1.DeregisterHostRequest
	(*Empty)(nil),                 // 8: discovery.v1.Empty
	(*ListHostsRequest)(nil),      // 9: discovery.v1.ListHostsRequest
	(*CapabilityFilter)(nil),      // 10: discovery.v1.CapabilityFilter
	(*ListHostsResponse)(nil),     // 11: discovery.v1.ListHostsResponse
	(*GetHostRequest)(nil),        // 12: discovery.v1.GetHostRequest
	(*WatchHostsRequest)(nil),     // 13: discovery.v1.WatchHostsRequest
	(*HostEvent)(nil),             // 14: discovery.v1.HostEvent
	(*HealthRequest)(nil),         // 15: discovery.v1.HealthRequest
	(*HealthResponse)(nil),        // 16: discovery.v1.HealthResponse
	(*HealthCheck)(nil),           // 17: discovery.v1.HealthCheck
}
var file_discovery_proto_depIdxs = []int32{
	1,  // 0: discovery.v1.RendezvousHost.capabilities:type_name -> discovery.v1.CapabilitiesSnapshot
	2,  // 1: discovery.v1.CapabilitiesSnapshot.gpus:type_name -> discovery.v1.GPUCapability
	3,  // 2: discovery.v1.CapabilitiesSnapshot.max_resolution:type_name -> discovery.v1.Resolution
	10, // 3: discovery.v1.ListHostsRequest.capability_filter:type_name -> discovery.v1.CapabilityFilter
	0,  // 4: discovery.v1.ListHostsResponse.hosts:type_name -> discovery.v1.RendezvousHost
	10, // 5: discovery.v1.WatchHostsRequest.capability_filter:type_name -> discovery.v1.CapabilityFilter
	0,  // 6: discovery.v1.HostEvent.host:type_name -> discovery.v1.RendezvousHost
	17, // 7: discovery.v1.HealthResponse.checks:type_name -> discovery.v1.HealthCheck
	0,  // 8: discovery.v1.RendezvousService.RegisterHost:input_type -> discovery.v1.RendezvousHost
	5,  // 9: discovery.v1.RendezvousService.Heartbeat:input_type -> discovery.v1.HeartbeatRequest
	7,  // 10: discovery.v1.RendezvousService.DeregisterHost:input_type -> discovery.v1.DeregisterHostRequest
	9,  // 11: discovery.v1.RendezvousService.ListHosts:input_type -> discovery.v1.ListHostsRequest
	12, // 12: discovery.v1.RendezvousService.GetHost:input_type -> discovery.v1.GetHostRequest
	13, // 13: discovery.v1.RendezvousService.WatchHosts:input_type -> discovery.v1.WatchHostsRequest
	15, // 14: discovery.v1.RendezvousService.Health:input_type -> discovery.v1.HealthRequest
	4,  // 15: discovery.v1.RendezvousService.RegisterHost:output_type -> discovery.v1.RegisterHostResponse
	6,  // 16: discovery.v1.RendezvousService.Heartbeat:output_type -> discovery.v1.HeartbeatResponse
	8,  // 17: discovery.v1.RendezvousService.DeregisterHost:output_type -> discovery.v1.Empty
	11, // 18: discovery.v1.RendezvousService.ListHosts:output_type -> discovery.v1.ListHostsResponse
	0,  // 19: discovery.v1.RendezvousService.GetHost:output_type -> discovery.v1.RendezvousHost
	14, // 20: discovery.v1.RendezvousService.WatchHosts:output_type -> discovery.v1.HostEvent
	16, // 21: discovery.v1.RendezvousService.Health:output_type -> discovery.v1.HealthResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
