// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.5
// source: hostagent.proto

package hostagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAgentService_RegisterHost_FullMethodName          = "/hostagent.v1.HostAgentService/RegisterHost"
	HostAgentService_UpdateHostStatus_FullMethodName      = "/hostagent.v1.HostAgentService/UpdateHostStatus"
	HostAgentService_DeregisterHost_FullMethodName        = "/hostagent.v1.HostAgentService/DeregisterHost"
	HostAgentService_ListInstalledGames_FullMethodName    = "/hostagent.v1.HostAgentService/ListInstalledGames"
	HostAgentService_LaunchGame_FullMethodName            = "/hostagent.v1.HostAgentService/LaunchGame"
	HostAgentService_TerminateGame_FullMethodName         = "/hostagent.v1.HostAgentService/TerminateGame"
	HostAgentService_GetGameStatus_FullMethodName         = "/hostagent.v1.HostAgentService/GetGameStatus"
	HostAgentService_CreateSession_FullMethodName         = "/hostagent.v1.HostAgentService/CreateSession"
	HostAgentService_GetSession_FullMethodName            = "/hostagent.v1.HostAgentService/GetSession"
	HostAgentService_ListSessions_FullMethodName          = "/hostagent.v1.HostAgentService/ListSessions"
	HostAgentService_TerminateSession_FullMethodName      = "/hostagent.v1.HostAgentService/TerminateSession"
	HostAgentService_AdvertiseCapabilities_FullMethodName = "/hostagent.v1.HostAgentService/AdvertiseCapabilities"
	HostAgentService_GetCapabilities_FullMethodName       = "/hostagent.v1.HostAgentService/GetCapabilities"
	HostAgentService_StartRecording_FullMethodName        = "/hostagent.v1.HostAgentService/StartRecording"
	HostAgentService_StopRecording_FullMethodName         = "/hostagent.v1.HostAgentService/StopRecording"
	HostAgentService_ListRecordings_FullMethodName        = "/hostagent.v1.HostAgentService/ListRecordings"
	HostAgentService_StreamHostTelemetry_FullMethodName   = "/hostagent.v1.HostAgentService/StreamHostTelemetry"
	HostAgentService_GetHostMetrics_FullMethodName        = "/hostagent.v1.HostAgentService/GetHostMetrics"
	HostAgentService_Health_FullMethodName                = "/hostagent.v1.HostAgentService/Health"
)

// HostAgentServiceClient is the client API for HostAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostAgentService manages host lifecycle, games, sessions, and recordings
type HostAgentServiceClient interface {
	// Lifecycle
	RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*Host, error)
	UpdateHostStatus(ctx context.Context, in *UpdateHostStatusRequest, opts ...grpc.CallOption) (*Host, error)
	DeregisterHost(ctx context.Context, in *DeregisterHostRequest, opts ...grpc.CallOption) (*Empty, error)
	// Game management
	ListInstalledGames(ctx context.Context, in *ListInstalledGamesRequest, opts ...grpc.CallOption) (*ListInstalledGamesResponse, error)
	LaunchGame(ctx context.Context, in *LaunchGameRequest, opts ...grpc.CallOption) (*LaunchGameResponse, error)
	TerminateGame(ctx context.Context, in *TerminateGameRequest, opts ...grpc.CallOption) (*TerminateGameResponse, error)
	GetGameStatus(ctx context.Context, in *GetGameStatusRequest, opts ...grpc.CallOption) (*GameStatus, error)
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// Capability
	AdvertiseCapabilities(ctx context.Context, in *AdvertiseCapabilitiesRequest, opts ...grpc.CallOption) (*CapabilityAck, error)
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesSnapshot, error)
	// Recording
	StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*Recording, error)
	StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*Recording, error)
	ListRecordings(ctx context.Context, in *ListRecordingsRequest, opts ...grpc.CallOption) (*ListRecordingsResponse, error)
	// Telemetry
	StreamHostTelemetry(ctx context.Context, in *StreamHostTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryFrame], error)
	GetHostMetrics(ctx context.Context, in *GetHostMetricsRequest, opts ...grpc.CallOption) (*HostMetrics, error)
	// Health
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type hostAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAgentServiceClient(cc grpc.ClientConnInterface) HostAgentServiceClient {
	return &hostAgentServiceClient{cc}
}

func (c *hostAgentServiceClient) RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAgentService_RegisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) UpdateHostStatus(ctx context.Context, in *UpdateHostStatusRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAgentService_UpdateHostStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) DeregisterHost(ctx context.Context, in *DeregisterHostRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAgentService_DeregisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) ListInstalledGames(ctx context.Context, in *ListInstalledGamesRequest, opts ...grpc.CallOption) (*ListInstalledGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstalledGamesResponse)
	err := c.cc.Invoke(ctx, HostAgentService_ListInstalledGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) LaunchGame(ctx context.Context, in *LaunchGameRequest, opts ...grpc.CallOption) (*LaunchGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchGameResponse)
	err := c.cc.Invoke(ctx, HostAgentService_LaunchGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) TerminateGame(ctx context.Context, in *TerminateGameRequest, opts ...grpc.CallOption) (*TerminateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateGameResponse)
	err := c.cc.Invoke(ctx, HostAgentService_TerminateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) GetGameStatus(ctx context.Context, in *GetGameStatusRequest, opts ...grpc.CallOption) (*GameStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameStatus)
	err := c.cc.Invoke(ctx, HostAgentService_GetGameStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, HostAgentService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, HostAgentService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, HostAgentService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, HostAgentService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) AdvertiseCapabilities(ctx context.Context, in *AdvertiseCapabilitiesRequest, opts ...grpc.CallOption) (*CapabilityAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityAck)
	err := c.cc.Invoke(ctx, HostAgentService_AdvertiseCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesSnapshot)
	err := c.cc.Invoke(ctx, HostAgentService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*Recording, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Recording)
	err := c.cc.Invoke(ctx, HostAgentService_StartRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*Recording, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Recording)
	err := c.cc.Invoke(ctx, HostAgentService_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) ListRecordings(ctx context.Context, in *ListRecordingsRequest, opts ...grpc.CallOption) (*ListRecordingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordingsResponse)
	err := c.cc.Invoke(ctx, HostAgentService_ListRecordings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) StreamHostTelemetry(ctx context.Context, in *StreamHostTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostAgentService_ServiceDesc.Streams[0], HostAgentService_StreamHostTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamHostTelemetryRequest, TelemetryFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostAgentService_StreamHostTelemetryClient = grpc.ServerStreamingClient[TelemetryFrame]

func (c *hostAgentServiceClient) GetHostMetrics(ctx context.Context, in *GetHostMetricsRequest, opts ...grpc.CallOption) (*HostMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostMetrics)
	err := c.cc.Invoke(ctx, HostAgentService_GetHostMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HostAgentService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAgentServiceServer is the server API for HostAgentService service.
// All implementations must embed UnimplementedHostAgentServiceServer
// for forward compatibility.
//
// HostAgentService manages host lifecycle, games, sessions, and recordings
type HostAgentServiceServer interface {
	// Lifecycle
	RegisterHost(context.Context, *RegisterHostRequest) (*Host, error)
	UpdateHostStatus(context.Context, *UpdateHostStatusRequest) (*Host, error)
	DeregisterHost(context.Context, *DeregisterHostRequest) (*Empty, error)
	// Game management
	ListInstalledGames(context.Context, *ListInstalledGamesRequest) (*ListInstalledGamesResponse, error)
	LaunchGame(context.Context, *LaunchGameRequest) (*LaunchGameResponse, error)
	TerminateGame(context.Context, *TerminateGameRequest) (*TerminateGameResponse, error)
	GetGameStatus(context.Context, *GetGameStatusRequest) (*GameStatus, error)
	// Session management
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*Session, error)
	// Capability
	AdvertiseCapabilities(context.Context, *AdvertiseCapabilitiesRequest) (*CapabilityAck, error)
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*CapabilitiesSnapshot, error)
	// Recording
	StartRecording(context.Context, *StartRecordingRequest) (*Recording, error)
	StopRecording(context.Context, *StopRecordingRequest) (*Recording, error)
	ListRecordings(context.Context, *ListRecordingsRequest) (*ListRecordingsResponse, error)
	// Telemetry
	StreamHostTelemetry(*StreamHostTelemetryRequest, grpc.ServerStreamingServer[TelemetryFrame]) error
	GetHostMetrics(context.Context, *GetHostMetricsRequest) (*HostMetrics, error)
	// Health
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHostAgentServiceServer()
}

// UnimplementedHostAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAgentServiceServer struct{}

func (UnimplementedHostAgentServiceServer) RegisterHost(context.Context, *RegisterHostRequest) (*Host, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHost not implemented")
}
func (UnimplementedHostAgentServiceServer) UpdateHostStatus(context.Context, *UpdateHostStatusRequest) (*Host, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHostStatus not implemented")
}
func (UnimplementedHostAgentServiceServer) DeregisterHost(context.Context, *DeregisterHostRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterHost not implemented")
}
func (UnimplementedHostAgentServiceServer) ListInstalledGames(context.Context, *ListInstalledGamesRequest) (*ListInstalledGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstalledGames not implemented")
}
func (UnimplementedHostAgentServiceServer) LaunchGame(context.Context, *LaunchGameRequest) (*LaunchGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LaunchGame not implemented")
}
func (UnimplementedHostAgentServiceServer) TerminateGame(context.Context, *TerminateGameRequest) (*TerminateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateGame not implemented")
}
func (UnimplementedHostAgentServiceServer) GetGameStatus(context.Context, *GetGameStatusRequest) (*GameStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameStatus not implemented")
}
func (UnimplementedHostAgentServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedHostAgentServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedHostAgentServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedHostAgentServiceServer) TerminateSession(context.Context, *TerminateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedHostAgentServiceServer) AdvertiseCapabilities(context.Context, *AdvertiseCapabilitiesRequest) (*CapabilityAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertiseCapabilities not implemented")
}
func (UnimplementedHostAgentServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*CapabilitiesSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedHostAgentServiceServer) StartRecording(context.Context, *StartRecordingRequest) (*Recording, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedHostAgentServiceServer) StopRecording(context.Context, *StopRecordingRequest) (*Recording, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedHostAgentServiceServer) ListRecordings(context.Context, *ListRecordingsRequest) (*ListRecordingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecordings not implemented")
}
func (UnimplementedHostAgentServiceServer) StreamHostTelemetry(*StreamHostTelemetryRequest, grpc.ServerStreamingServer[TelemetryFrame]) error {
	return status.Error(codes.Unimplemented, "method StreamHostTelemetry not implemented")
}
func (UnimplementedHostAgentServiceServer) GetHostMetrics(context.Context, *GetHostMetricsRequest) (*HostMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostMetrics not implemented")
}
func (UnimplementedHostAgentServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedHostAgentServiceServer) mustEmbedUnimplementedHostAgentServiceServer() {}
func (UnimplementedHostAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeHostAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAgentServiceServer will
// result in compilation errors.
type UnsafeHostAgentServiceServer interface {
	mustEmbedUnimplementedHostAgentServiceServer()
}

func RegisterHostAgentServiceServer(s grpc.ServiceRegistrar, srv HostAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedHostAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAgentService_ServiceDesc, srv)
}

func _HostAgentService_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_RegisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).RegisterHost(ctx, req.(*RegisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_UpdateHostStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).UpdateHostStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_UpdateHostStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).UpdateHostStatus(ctx, req.(*UpdateHostStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_DeregisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).DeregisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_DeregisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).DeregisterHost(ctx, req.(*DeregisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_ListInstalledGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstalledGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).ListInstalledGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_ListInstalledGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).ListInstalledGames(ctx, req.(*ListInstalledGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_LaunchGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).LaunchGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_LaunchGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).LaunchGame(ctx, req.(*LaunchGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_TerminateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).TerminateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_TerminateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).TerminateGame(ctx, req.(*TerminateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_GetGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).GetGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_GetGameStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).GetGameStatus(ctx, req.(*GetGameStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_AdvertiseCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiseCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).AdvertiseCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_AdvertiseCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).AdvertiseCapabilities(ctx, req.(*AdvertiseCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_StartRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).StartRecording(ctx, req.(*StartRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).StopRecording(ctx, req.(*StopRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_ListRecordings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).ListRecordings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_ListRecordings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).ListRecordings(ctx, req.(*ListRecordingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_StreamHostTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamHostTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostAgentServiceServer).StreamHostTelemetry(m, &grpc.GenericServerStream[StreamHostTelemetryRequest, TelemetryFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostAgentService_StreamHostTelemetryServer = grpc.ServerStreamingServer[TelemetryFrame]

func _HostAgentService_GetHostMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).GetHostMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_GetHostMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).GetHostMetrics(ctx, req.(*GetHostMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgentService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgentService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAgentService_ServiceDesc is the grpc.ServiceDesc for HostAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostagent.v1.HostAgentService",
	HandlerType: (*HostAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHost",
			Handler:    _HostAgentService_RegisterHost_Handler,
		},
		{
			MethodName: "UpdateHostStatus",
			Handler:    _HostAgentService_UpdateHostStatus_Handler,
		},
		{
			MethodName: "DeregisterHost",
			Handler:    _HostAgentService_DeregisterHost_Handler,
		},
		{
			MethodName: "ListInstalledGames",
			Handler:    _HostAgentService_ListInstalledGames_Handler,
		},
		{
			MethodName: "LaunchGame",
			Handler:    _HostAgentService_LaunchGame_Handler,
		},
		{
			MethodName: "TerminateGame",
			Handler:    _HostAgentService_TerminateGame_Handler,
		},
		{
			MethodName: "GetGameStatus",
			Handler:    _HostAgentService_GetGameStatus_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _HostAgentService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _HostAgentService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _HostAgentService_ListSessions_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _HostAgentService_TerminateSession_Handler,
		},
		{
			MethodName: "AdvertiseCapabilities",
			Handler:    _HostAgentService_AdvertiseCapabilities_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _HostAgentService_GetCapabilities_Handler,
		},
		{
			MethodName: "StartRecording",
			Handler:    _HostAgentService_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _HostAgentService_StopRecording_Handler,
		},
		{
			MethodName: "ListRecordings",
			Handler:    _HostAgentService_ListRecordings_Handler,
		},
		{
			MethodName: "GetHostMetrics",
			Handler:    _HostAgentService_GetHostMetrics_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _HostAgentService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHostTelemetry",
			Handler:       _HostAgentService_StreamHostTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hostagent.proto",
}
