// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: catalog.proto

package catalogizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        *GameFilter            `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ListGamesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListGamesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGamesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGamesRequest) GetFilter() *GameFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListGamesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GameFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         []string               `protobuf:"bytes,1,rep,name=store,proto3" json:"store,omitempty"`
	Genre         []string               `protobuf:"bytes,2,rep,name=genre,proto3" json:"genre,omitempty"`
	Hdr           bool                   `protobuf:"varint,3,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Dualsense     bool                   `protobuf:"varint,4,opt,name=dualsense,proto3" json:"dualsense,omitempty"`
	InstalledOnly bool                   `protobuf:"varint,5,opt,name=installed_only,json=installedOnly,proto3" json:"installed_only,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,6,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameFilter) Reset() {
	*x = GameFilter{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFilter) ProtoMessage() {}

func (x *GameFilter) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFilter.ProtoReflect.Descriptor instead.
func (*GameFilter) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GameFilter) GetStore() []string {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *GameFilter) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *GameFilter) GetHdr() bool {
	if x != nil {
		return x.Hdr
	}
	return false
}

func (x *GameFilter) GetDualsense() bool {
	if x != nil {
		return x.Dualsense
	}
	return false
}

func (x *GameFilter) GetInstalledOnly() bool {
	if x != nil {
		return x.InstalledOnly
	}
	return false
}

func (x *GameFilter) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *ListGamesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListGamesResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	IncludeAssets bool                   `protobuf:"varint,3,opt,name=include_assets,json=includeAssets,proto3" json:"include_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameRequest) GetIncludeAssets() bool {
	if x != nil {
		return x.IncludeAssets
	}
	return false
}

type Game struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GameId               string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	TenantId             string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Store                string                 `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	StoreAppId           string                 `protobuf:"bytes,4,opt,name=store_app_id,json=storeAppId,proto3" json:"store_app_id,omitempty"`
	Title                string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Description          string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Developer            string                 `protobuf:"bytes,8,opt,name=developer,proto3" json:"developer,omitempty"`
	Publisher            string                 `protobuf:"bytes,9,opt,name=publisher,proto3" json:"publisher,omitempty"`
	ReleaseDate          string                 `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Genres               []string               `protobuf:"bytes,11,rep,name=genres,proto3" json:"genres,omitempty"`
	Tags                 []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	CoverArtUrl          string                 `protobuf:"bytes,13,opt,name=cover_art_url,json=coverArtUrl,proto3" json:"cover_art_url,omitempty"`
	ScreenshotUrls       []string               `protobuf:"bytes,14,rep,name=screenshot_urls,json=screenshotUrls,proto3" json:"screenshot_urls,omitempty"`
	VideoUrls            []string               `protobuf:"bytes,15,rep,name=video_urls,json=videoUrls,proto3" json:"video_urls,omitempty"`
	MinRequirements      *SystemRequirements    `protobuf:"bytes,16,opt,name=min_requirements,json=minRequirements,proto3" json:"min_requirements,omitempty"`
	RecRequirements      *SystemRequirements    `protobuf:"bytes,17,opt,name=rec_requirements,json=recRequirements,proto3" json:"rec_requirements,omitempty"`
	SupportsHdr          bool                   `protobuf:"varint,18,opt,name=supports_hdr,json=supportsHdr,proto3" json:"supports_hdr,omitempty"`
	SupportsAtmos        bool                   `protobuf:"varint,19,opt,name=supports_atmos,json=supportsAtmos,proto3" json:"supports_atmos,omitempty"`
	SupportsDualsense    bool                   `protobuf:"varint,20,opt,name=supports_dualsense,json=supportsDualsense,proto3" json:"supports_dualsense,omitempty"`
	SupportedControllers []string               `protobuf:"bytes,21,rep,name=supported_controllers,json=supportedControllers,proto3" json:"supported_controllers,omitempty"`
	IsInstalled          bool                   `protobuf:"varint,22,opt,name=is_installed,json=isInstalled,proto3" json:"is_installed,omitempty"`
	PlaytimeSeconds      int64                  `protobuf:"varint,23,opt,name=playtime_seconds,json=playtimeSeconds,proto3" json:"playtime_seconds,omitempty"`
	LastPlayedAt         string                 `protobuf:"bytes,24,opt,name=last_played_at,json=lastPlayedAt,proto3" json:"last_played_at,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,25,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Game) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Game) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Game) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *Game) GetStoreAppId() string {
	if x != nil {
		return x.StoreAppId
	}
	return ""
}

func (x *Game) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Game) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *Game) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Game) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Game) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Game) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Game) GetCoverArtUrl() string {
	if x != nil {
		return x.CoverArtUrl
	}
	return ""
}

func (x *Game) GetScreenshotUrls() []string {
	if x != nil {
		return x.ScreenshotUrls
	}
	return nil
}

func (x *Game) GetVideoUrls() []string {
	if x != nil {
		return x.VideoUrls
	}
	return nil
}

func (x *Game) GetMinRequirements() *SystemRequirements {
	if x != nil {
		return x.MinRequirements
	}
	return nil
}

func (x *Game) GetRecRequirements() *SystemRequirements {
	if x != nil {
		return x.RecRequirements
	}
	return nil
}

func (x *Game) GetSupportsHdr() bool {
	if x != nil {
		return x.SupportsHdr
	}
	return false
}

func (x *Game) GetSupportsAtmos() bool {
	if x != nil {
		return x.SupportsAtmos
	}
	return false
}

func (x *Game) GetSupportsDualsense() bool {
	if x != nil {
		return x.SupportsDualsense
	}
	return false
}

func (x *Game) GetSupportedControllers() []string {
	if x != nil {
		return x.SupportedControllers
	}
	return nil
}

func (x *Game) GetIsInstalled() bool {
	if x != nil {
		return x.IsInstalled
	}
	return false
}

func (x *Game) GetPlaytimeSeconds() int64 {
	if x != nil {
		return x.PlaytimeSeconds
	}
	return 0
}

func (x *Game) GetLastPlayedAt() string {
	if x != nil {
		return x.LastPlayedAt
	}
	return ""
}

func (x *Game) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SystemRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gpu           string                 `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"`
	RamGb         int32                  `protobuf:"varint,2,opt,name=ram_gb,json=ramGb,proto3" json:"ram_gb,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	StorageGb     string                 `protobuf:"bytes,4,opt,name=storage_gb,json=storageGb,proto3" json:"storage_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemRequirements) Reset() {
	*x = SystemRequirements{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemRequirements) ProtoMessage() {}

func (x *SystemRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemRequirements.ProtoReflect.Descriptor instead.
func (*SystemRequirements) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *SystemRequirements) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *SystemRequirements) GetRamGb() int32 {
	if x != nil {
		return x.RamGb
	}
	return 0
}

func (x *SystemRequirements) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemRequirements) GetStorageGb() string {
	if x != nil {
		return x.StorageGb
	}
	return ""
}

type SearchGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Facets        []string               `protobuf:"bytes,5,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGamesRequest) Reset() {
	*x = SearchGamesRequest{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGamesRequest) ProtoMessage() {}

func (x *SearchGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGamesRequest.ProtoReflect.Descriptor instead.
func (*SearchGamesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *SearchGamesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchGamesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchGamesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchGamesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchGamesRequest) GetFacets() []string {
	if x != nil {
		return x.Facets
	}
	return nil
}

type SearchGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Game                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Facets        map[string]*Facet      `protobuf:"bytes,2,rep,name=facets,proto3" json:"facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGamesResponse) Reset() {
	*x = SearchGamesResponse{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGamesResponse) ProtoMessage() {}

func (x *SearchGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGamesResponse.ProtoReflect.Descriptor instead.
func (*SearchGamesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *SearchGamesResponse) GetResults() []*Game {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchGamesResponse) GetFacets() map[string]*Facet {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *SearchGamesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchGamesResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *SearchGamesResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type Facet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*FacetValue          `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *Facet) GetValues() []*FacetValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type FacetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetValue) Reset() {
	*x = FacetValue{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetValue) ProtoMessage() {}

func (x *FacetValue) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetValue.ProtoReflect.Descriptor instead.
func (*FacetValue) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *FacetValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FacetValue) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetGameAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	AssetTypes    []string               `protobuf:"bytes,3,rep,name=asset_types,json=assetTypes,proto3" json:"asset_types,omitempty"`
	MaxResolution string                 `protobuf:"bytes,4,opt,name=max_resolution,json=maxResolution,proto3" json:"max_resolution,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameAssetsRequest) Reset() {
	*x = GetGameAssetsRequest{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameAssetsRequest) ProtoMessage() {}

func (x *GetGameAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetGameAssetsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetGameAssetsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetGameAssetsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameAssetsRequest) GetAssetTypes() []string {
	if x != nil {
		return x.AssetTypes
	}
	return nil
}

func (x *GetGameAssetsRequest) GetMaxResolution() string {
	if x != nil {
		return x.MaxResolution
	}
	return ""
}

func (x *GetGameAssetsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GameAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Assets        []*Asset               `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	CdnTtlSeconds int32                  `protobuf:"varint,3,opt,name=cdn_ttl_seconds,json=cdnTtlSeconds,proto3" json:"cdn_ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAssets) Reset() {
	*x = GameAssets{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAssets) ProtoMessage() {}

func (x *GameAssets) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAssets.ProtoReflect.Descriptor instead.
func (*GameAssets) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *GameAssets) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameAssets) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GameAssets) GetCdnTtlSeconds() int32 {
	if x != nil {
		return x.CdnTtlSeconds
	}
	return 0
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *Asset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Asset) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Asset) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Asset) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Asset) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Asset) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GetTenantCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantCatalogRequest) Reset() {
	*x = GetTenantCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantCatalogRequest) ProtoMessage() {}

func (x *GetTenantCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetTenantCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *GetTenantCatalogRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TenantCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Filter        *CatalogFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	TotalGames    int64                  `protobuf:"varint,3,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	LastSyncAt    string                 `protobuf:"bytes,4,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCatalog) Reset() {
	*x = TenantCatalog{}
	mi := &file_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCatalog) ProtoMessage() {}

func (x *TenantCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCatalog.ProtoReflect.Descriptor instead.
func (*TenantCatalog) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *TenantCatalog) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantCatalog) GetFilter() *CatalogFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *TenantCatalog) GetTotalGames() int64 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *TenantCatalog) GetLastSyncAt() string {
	if x != nil {
		return x.LastSyncAt
	}
	return ""
}

type CatalogFilter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowedStores    []string               `protobuf:"bytes,1,rep,name=allowed_stores,json=allowedStores,proto3" json:"allowed_stores,omitempty"`
	AllowedGenres    []string               `protobuf:"bytes,2,rep,name=allowed_genres,json=allowedGenres,proto3" json:"allowed_genres,omitempty"`
	ExcludedTags     []string               `protobuf:"bytes,3,rep,name=excluded_tags,json=excludedTags,proto3" json:"excluded_tags,omitempty"`
	RatingMax        int32                  `protobuf:"varint,4,opt,name=rating_max,json=ratingMax,proto3" json:"rating_max,omitempty"`
	RequireHdr       bool                   `protobuf:"varint,5,opt,name=require_hdr,json=requireHdr,proto3" json:"require_hdr,omitempty"`
	RequireDualsense bool                   `protobuf:"varint,6,opt,name=require_dualsense,json=requireDualsense,proto3" json:"require_dualsense,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CatalogFilter) Reset() {
	*x = CatalogFilter{}
	mi := &file_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogFilter) ProtoMessage() {}

func (x *CatalogFilter) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogFilter.ProtoReflect.Descriptor instead.
func (*CatalogFilter) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *CatalogFilter) GetAllowedStores() []string {
	if x != nil {
		return x.AllowedStores
	}
	return nil
}

func (x *CatalogFilter) GetAllowedGenres() []string {
	if x != nil {
		return x.AllowedGenres
	}
	return nil
}

func (x *CatalogFilter) GetExcludedTags() []string {
	if x != nil {
		return x.ExcludedTags
	}
	return nil
}

func (x *CatalogFilter) GetRatingMax() int32 {
	if x != nil {
		return x.RatingMax
	}
	return 0
}

func (x *CatalogFilter) GetRequireHdr() bool {
	if x != nil {
		return x.RequireHdr
	}
	return false
}

func (x *CatalogFilter) GetRequireDualsense() bool {
	if x != nil {
		return x.RequireDualsense
	}
	return false
}

type UpdateTenantCatalogFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Filter        *CatalogFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantCatalogFilterRequest) Reset() {
	*x = UpdateTenantCatalogFilterRequest{}
	mi := &file_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantCatalogFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantCatalogFilterRequest) ProtoMessage() {}

func (x *UpdateTenantCatalogFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantCatalogFilterRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantCatalogFilterRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTenantCatalogFilterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantCatalogFilterRequest) GetFilter() *CatalogFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Checks        []*HealthCheck         `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetChecks() []*HealthCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *HealthCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\x0ecatalogizer.v1\"\xba\x01\n" +
	"\x10ListGamesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x122\n" +
	"\x06filter\x18\x04 \x01(\v2\x1a.catalogizer.v1.GameFilterR\x06filter\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\"\xb2\x01\n" +
	"\n" +
	"GameFilter\x12\x14\n" +
	"\x05store\x18\x01 \x03(\tR\x05store\x12\x14\n" +
	"\x05genre\x18\x02 \x03(\tR\x05genre\x12\x10\n" +
	"\x03hdr\x18\x03 \x01(\bR\x03hdr\x12\x1c\n" +
	"\tdualsense\x18\x04 \x01(\bR\tdualsense\x12%\n" +
	"\x0einstalled_only\x18\x05 \x01(\bR\rinstalledOnly\x12!\n" +
	"\fsearch_query\x18\x06 \x01(\tR\vsearchQuery\"\x86\x01\n" +
	"\x11ListGamesResponse\x12*\n" +
	"\x05games\x18\x01 \x03(\v2\x14.catalogizer.v1.GameR\x05games\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\"m\n" +
	"\x0eGetGameRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12%\n" +
	"\x0einclude_assets\x18\x03 \x01(\bR\rincludeAssets\"\xf4\a\n" +
	"\x04Game\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05store\x18\x03 \x01(\tR\x05store\x12 \n" +
	"\fstore_app_id\x18\x04 \x01(\tR\n" +
	"storeAppId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1c\n" +
	"\tdeveloper\x18\b \x01(\tR\tdeveloper\x12\x1c\n" +
	"\tpublisher\x18\t \x01(\tR\tpublisher\x12!\n" +
	"\frelease_date\x18\n" +
	" \x01(\tR\vreleaseDate\x12\x16\n" +
	"\x06genres\x18\v \x03(\tR\x06genres\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\"\n" +
	"\rcover_art_url\x18\r \x01(\tR\vcoverArtUrl\x12'\n" +
	"\x0fscreenshot_urls\x18\x0e \x03(\tR\x0escreenshotUrls\x12\x1d\n" +
	"\n" +
	"video_urls\x18\x0f \x03(\tR\tvideoUrls\x12M\n" +
	"\x10min_requirements\x18\x10 \x01(\v2\".catalogizer.v1.SystemRequirementsR\x0fminRequirements\x12M\n" +
	"\x10rec_requirements\x18\x11 \x01(\v2\".catalogizer.v1.SystemRequirementsR\x0frecRequirements\x12!\n" +
	"\fsupports_hdr\x18\x12 \x01(\bR\vsupportsHdr\x12%\n" +
	"\x0esupports_atmos\x18\x13 \x01(\bR\rsupportsAtmos\x12-\n" +
	"\x12supports_dualsense\x18\x14 \x01(\bR\x11supportsDualsense\x123\n" +
	"\x15supported_controllers\x18\x15 \x03(\tR\x14supportedControllers\x12!\n" +
	"\fis_installed\x18\x16 \x01(\bR\visInstalled\x12)\n" +
	"\x10playtime_seconds\x18\x17 \x01(\x03R\x0fplaytimeSeconds\x12$\n" +
	"\x0elast_played_at\x18\x18 \x01(\tR\flastPlayedAt\x12>\n" +
	"\bmetadata\x18\x19 \x03(\v2\".catalogizer.v1.Game.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x12SystemRequirements\x12\x10\n" +
	"\x03gpu\x18\x01 \x01(\tR\x03gpu\x12\x15\n" +
	"\x06ram_gb\x18\x02 \x01(\x05R\x05ramGb\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"storage_gb\x18\x04 \x01(\tR\tstorageGb\"\x9b\x01\n" +
	"\x12SearchGamesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06facets\x18\x05 \x03(\tR\x06facets\"\xc6\x02\n" +
	"\x13SearchGamesResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.catalogizer.v1.GameR\aresults\x12G\n" +
	"\x06facets\x18\x02 \x03(\v2/.catalogizer.v1.SearchGamesResponse.FacetsEntryR\x06facets\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05R\tlatencyMs\x1aP\n" +
	"\vFacetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.catalogizer.v1.FacetR\x05value:\x028\x01\";\n" +
	"\x05Facet\x122\n" +
	"\x06values\x18\x01 \x03(\v2\x1a.catalogizer.v1.FacetValueR\x06values\"8\n" +
	"\n" +
	"FacetValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xac\x01\n" +
	"\x14GetGameAssetsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vasset_types\x18\x03 \x03(\tR\n" +
	"assetTypes\x12%\n" +
	"\x0emax_resolution\x18\x04 \x01(\tR\rmaxResolution\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"|\n" +
	"\n" +
	"GameAssets\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12-\n" +
	"\x06assets\x18\x02 \x03(\v2\x15.catalogizer.v1.AssetR\x06assets\x12&\n" +
	"\x0fcdn_ttl_seconds\x18\x03 \x01(\x05R\rcdnTtlSeconds\"\x92\x01\n" +
	"\x05Asset\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"6\n" +
	"\x17GetTenantCatalogRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xa6\x01\n" +
	"\rTenantCatalog\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x125\n" +
	"\x06filter\x18\x02 \x01(\v2\x1d.catalogizer.v1.CatalogFilterR\x06filter\x12\x1f\n" +
	"\vtotal_games\x18\x03 \x01(\x03R\n" +
	"totalGames\x12 \n" +
	"\flast_sync_at\x18\x04 \x01(\tR\n" +
	"lastSyncAt\"\xef\x01\n" +
	"\rCatalogFilter\x12%\n" +
	"\x0eallowed_stores\x18\x01 \x03(\tR\rallowedStores\x12%\n" +
	"\x0eallowed_genres\x18\x02 \x03(\tR\rallowedGenres\x12#\n" +
	"\rexcluded_tags\x18\x03 \x03(\tR\fexcludedTags\x12\x1d\n" +
	"\n" +
	"rating_max\x18\x04 \x01(\x05R\tratingMax\x12\x1f\n" +
	"\vrequire_hdr\x18\x05 \x01(\bR\n" +
	"requireHdr\x12+\n" +
	"\x11require_dualsense\x18\x06 \x01(\bR\x10requireDualsense\"v\n" +
	" UpdateTenantCatalogFilterRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x125\n" +
	"\x06filter\x18\x02 \x01(\v2\x1d.catalogizer.v1.CatalogFilterR\x06filter\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"]\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x123\n" +
	"\x06checks\x18\x02 \x03(\v2\x1b.catalogizer.v1.HealthCheckR\x06checks\"Q\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail2\xe1\x04\n" +
	"\x0eCatalogService\x12P\n" +
	"\tListGames\x12 .catalogizer.v1.ListGamesRequest\x1a!.catalogizer.v1.ListGamesResponse\x12?\n" +
	"\aGetGame\x12\x1e.catalogizer.v1.GetGameRequest\x1a\x14.catalogizer.v1.Game\x12V\n" +
	"\vSearchGames\x12\".catalogizer.v1.SearchGamesRequest\x1a#.catalogizer.v1.SearchGamesResponse\x12Q\n" +
	"\rGetGameAssets\x12$.catalogizer.v1.GetGameAssetsRequest\x1a\x1a.catalogizer.v1.GameAssets\x12Z\n" +
	"\x10GetTenantCatalog\x12'.catalogizer.v1.GetTenantCatalogRequest\x1a\x1d.catalogizer.v1.TenantCatalog\x12l\n" +
	"\x19UpdateTenantCatalogFilter\x120.catalogizer.v1.UpdateTenantCatalogFilterRequest\x1a\x1d.catalogizer.v1.TenantCatalog\x12G\n" +
	"\x06Health\x12\x1d.catalogizer.v1.HealthRequest\x1a\x1e.catalogizer.v1.HealthResponseBEZCgithub.com/HelixDevelopment/HelixPlay/pkg/protocol/v1;catalogizerv1b\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_catalog_proto_goTypes = []any{
	(*ListGamesRequest)(nil),                 // 0: catalogizer.v1.ListGamesRequest
	(*GameFilter)(nil),                       // 1: catalogizer.v1.GameFilter
	(*ListGamesResponse)(nil),                // 2: catalogizer.v1.ListGamesResponse
	(*GetGameRequest)(nil),                   // 3: catalogizer.v1.GetGameRequest
	(*Game)(nil),                             // 4: catalogizer.v1.Game
	(*SystemRequirements)(nil),               // 5: catalogizer.v1.SystemRequirements
	(*SearchGamesRequest)(nil),               // 6: catalogizer.v1.SearchGamesRequest
	(*SearchGamesResponse)(nil),              // 7: catalogizer.v1.SearchGamesResponse
	(*Facet)(nil),                            // 8: catalogizer.v1.Facet
	(*FacetValue)(nil),                       // 9: catalogizer.v1.FacetValue
	(*GetGameAssetsRequest)(nil),             // 10: catalogizer.v1.GetGameAssetsRequest
	(*GameAssets)(nil),                       // 11: catalogizer.v1.GameAssets
	(*Asset)(nil),                            // 12: catalogizer.v1.Asset
	(*GetTenantCatalogRequest)(nil),          // 13: catalogizer.v1.GetTenantCatalogRequest
	(*TenantCatalog)(nil),                    // 14: catalogizer.v1.TenantCatalog
	(*CatalogFilter)(nil),                    // 15: catalogizer.v1.CatalogFilter
	(*UpdateTenantCatalogFilterRequest)(nil), // 16: catalogizer.v1.UpdateTenantCatalogFilterRequest
	(*HealthRequest)(nil),                    // 17: catalogizer.v1.HealthRequest
	(*HealthResponse)(nil),                   // 18: catalogizer.v1.HealthResponse
	(*HealthCheck)(nil),                      // 19: catalogizer.v1.HealthCheck
	nil,                                      // 20: catalogizer.v1.Game.MetadataEntry
	nil,                                      // 21: catalogizer.v1.SearchGamesResponse.FacetsEntry
}
var file_catalog_proto_depIdxs = []int32{
	1,  // 0: catalogizer.v1.ListGamesRequest.filter:type_name -> catalogizer.v1.GameFilter
	4,  // 1: catalogizer.v1.ListGamesResponse.games:type_name -> catalogizer.v1.Game
	5,  // 2: catalogizer.v1.Game.min_requirements:type_name -> catalogizer.v1.SystemRequirements
	5,  // 3: catalogizer.v1.Game.rec_requirements:type_name -> catalogizer.v1.SystemRequirements
	20, // 4: catalogizer.v1.Game.metadata:type_name -> catalogizer.v1.Game.MetadataEntry
	4,  // 5: catalogizer.v1.SearchGamesResponse.results:type_name -> catalogizer.v1.Game
	21, // 6: catalogizer.v1.SearchGamesResponse.facets:type_name -> catalogizer.v1.SearchGamesResponse.FacetsEntry
	9,  // 7: catalogizer.v1.Facet.values:type_name -> catalogizer.v1.FacetValue
	12, // 8: catalogizer.v1.GameAssets.assets:type_name -> catalogizer.v1.Asset
	15, // 9: catalogizer.v1.TenantCatalog.filter:type_name -> catalogizer.v1.CatalogFilter
	15, // 10: catalogizer.v1.UpdateTenantCatalogFilterRequest.filter:type_name -> catalogizer.v1.CatalogFilter
	19, // 11: catalogizer.v1.HealthResponse.checks:type_name -> catalogizer.v1.HealthCheck
	8,  // 12: catalogizer.v1.SearchGamesResponse.FacetsEntry.value:type_name -> catalogizer.v1.Facet
	0,  // 13: catalogizer.v1.CatalogService.ListGames:input_type -> catalogizer.v1.ListGamesRequest
	3,  // 14: catalogizer.v1.CatalogService.GetGame:input_type -> catalogizer.v1.GetGameRequest
	6,  // 15: catalogizer.v1.CatalogService.SearchGames:input_type -> catalogizer.v1.SearchGamesRequest
	10, // 16: catalogizer.v1.CatalogService.GetGameAssets:input_type -> catalogizer.v1.GetGameAssetsRequest
	13, // 17: catalogizer.v1.CatalogService.GetTenantCatalog:input_type -> catalogizer.v1.GetTenantCatalogRequest
	16, // 18: catalogizer.v1.CatalogService.UpdateTenantCatalogFilter:input_type -> catalogizer.v1.UpdateTenantCatalogFilterRequest
	17, // 19: catalogizer.v1.CatalogService.Health:input_type -> catalogizer.v1.HealthRequest
	2,  // 20: catalogizer.v1.CatalogService.ListGames:output_type -> catalogizer.v1.ListGamesResponse
	4,  // 21: catalogizer.v1.CatalogService.GetGame:output_type -> catalogizer.v1.Game
	7,  // 22: catalogizer.v1.CatalogService.SearchGames:output_type -> catalogizer.v1.SearchGamesResponse
	11, // 23: catalogizer.v1.CatalogService.GetGameAssets:output_type -> catalogizer.v1.GameAssets
	14, // 24: catalogizer.v1.CatalogService.GetTenantCatalog:output_type -> catalogizer.v1.TenantCatalog
	14, // 25: catalogizer.v1.CatalogService.UpdateTenantCatalogFilter:output_type -> catalogizer.v1.TenantCatalog
	18, // 26: catalogizer.v1.CatalogService.Health:output_type -> catalogizer.v1.HealthResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
