// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.5
// source: catalog.proto

package catalogizerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_ListGames_FullMethodName                 = "/catalogizer.v1.CatalogService/ListGames"
	CatalogService_GetGame_FullMethodName                   = "/catalogizer.v1.CatalogService/GetGame"
	CatalogService_SearchGames_FullMethodName               = "/catalogizer.v1.CatalogService/SearchGames"
	CatalogService_GetGameAssets_FullMethodName             = "/catalogizer.v1.CatalogService/GetGameAssets"
	CatalogService_GetTenantCatalog_FullMethodName          = "/catalogizer.v1.CatalogService/GetTenantCatalog"
	CatalogService_UpdateTenantCatalogFilter_FullMethodName = "/catalogizer.v1.CatalogService/UpdateTenantCatalogFilter"
	CatalogService_Health_FullMethodName                    = "/catalogizer.v1.CatalogService/Health"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CatalogService proxy to HelixDevelopment/Catalogizer
type CatalogServiceClient interface {
	ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error)
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*Game, error)
	SearchGames(ctx context.Context, in *SearchGamesRequest, opts ...grpc.CallOption) (*SearchGamesResponse, error)
	GetGameAssets(ctx context.Context, in *GetGameAssetsRequest, opts ...grpc.CallOption) (*GameAssets, error)
	GetTenantCatalog(ctx context.Context, in *GetTenantCatalogRequest, opts ...grpc.CallOption) (*TenantCatalog, error)
	UpdateTenantCatalogFilter(ctx context.Context, in *UpdateTenantCatalogFilterRequest, opts ...grpc.CallOption) (*TenantCatalog, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGamesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, CatalogService_GetGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchGames(ctx context.Context, in *SearchGamesRequest, opts ...grpc.CallOption) (*SearchGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGamesResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetGameAssets(ctx context.Context, in *GetGameAssetsRequest, opts ...grpc.CallOption) (*GameAssets, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameAssets)
	err := c.cc.Invoke(ctx, CatalogService_GetGameAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetTenantCatalog(ctx context.Context, in *GetTenantCatalogRequest, opts ...grpc.CallOption) (*TenantCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantCatalog)
	err := c.cc.Invoke(ctx, CatalogService_GetTenantCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateTenantCatalogFilter(ctx context.Context, in *UpdateTenantCatalogFilterRequest, opts ...grpc.CallOption) (*TenantCatalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantCatalog)
	err := c.cc.Invoke(ctx, CatalogService_UpdateTenantCatalogFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CatalogService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
//
// CatalogService proxy to HelixDevelopment/Catalogizer
type CatalogServiceServer interface {
	ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error)
	GetGame(context.Context, *GetGameRequest) (*Game, error)
	SearchGames(context.Context, *SearchGamesRequest) (*SearchGamesResponse, error)
	GetGameAssets(context.Context, *GetGameAssetsRequest) (*GameAssets, error)
	GetTenantCatalog(context.Context, *GetTenantCatalogRequest) (*TenantCatalog, error)
	UpdateTenantCatalogFilter(context.Context, *UpdateTenantCatalogFilterRequest) (*TenantCatalog, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGames not implemented")
}
func (UnimplementedCatalogServiceServer) GetGame(context.Context, *GetGameRequest) (*Game, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGame not implemented")
}
func (UnimplementedCatalogServiceServer) SearchGames(context.Context, *SearchGamesRequest) (*SearchGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGames not implemented")
}
func (UnimplementedCatalogServiceServer) GetGameAssets(context.Context, *GetGameAssetsRequest) (*GameAssets, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameAssets not implemented")
}
func (UnimplementedCatalogServiceServer) GetTenantCatalog(context.Context, *GetTenantCatalogRequest) (*TenantCatalog, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantCatalog not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateTenantCatalogFilter(context.Context, *UpdateTenantCatalogFilterRequest) (*TenantCatalog, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenantCatalogFilter not implemented")
}
func (UnimplementedCatalogServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListGames(ctx, req.(*ListGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchGames(ctx, req.(*SearchGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetGameAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetGameAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetGameAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetGameAssets(ctx, req.(*GetGameAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetTenantCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTenantCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTenantCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTenantCatalog(ctx, req.(*GetTenantCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateTenantCatalogFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantCatalogFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateTenantCatalogFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateTenantCatalogFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateTenantCatalogFilter(ctx, req.(*UpdateTenantCatalogFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogizer.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGames",
			Handler:    _CatalogService_ListGames_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _CatalogService_GetGame_Handler,
		},
		{
			MethodName: "SearchGames",
			Handler:    _CatalogService_SearchGames_Handler,
		},
		{
			MethodName: "GetGameAssets",
			Handler:    _CatalogService_GetGameAssets_Handler,
		},
		{
			MethodName: "GetTenantCatalog",
			Handler:    _CatalogService_GetTenantCatalog_Handler,
		},
		{
			MethodName: "UpdateTenantCatalogFilter",
			Handler:    _CatalogService_UpdateTenantCatalogFilter_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CatalogService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
