// SPDX-FileCopyrightText: 2026 Milos Vasic
// SPDX-License-Identifier: Apache-2.0

// AST-based empty function body scanner.
//
// This tool uses go/ast to precisely detect functions and methods whose
// bodies contain no executable statements. It is strictly more accurate
// than the regex-based check in anti-bluff-scan.sh because it:
//
//   1. Understands Go syntax — won't be tricked by strings or comments.
//   2. Distinguishes truly empty blocks from blocks that only contain
//      comments (both are violations, but AST detection is explicit).
//   3. Handles generated files, build tags, and cgo correctly.
//
// Constitution §1.1.1: empty function bodies are forbidden unless the
// identifier contains Noop, NoOp, Mock, Stub, or is func main().
//
// Usage:
//   go run scripts/ast_empty_body_scan.go ./...
//   go run scripts/ast_empty_body_scan.go -exclude=vendor,generated pkg/...
//
// Exit code: 0 = no violations, 1 = violations found.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

var (
	excludeDirs   = flag.String("exclude", "vendor,node_modules,dist,build,.git", "comma-separated directory names to skip")
	excludeSuffix = flag.String("exclude-suffix", "_test.go,.pb.go,bindings.go", "comma-separated file suffixes to skip")
	verbose       = flag.Bool("v", false, "verbose output")
)

type violation struct {
	pos    token.Position
	kind   string // "func" or "method"
	name   string
	reason string
}

func main() {
	flag.Parse()
	patterns := flag.Args()
	if len(patterns) == 0 {
		patterns = []string{"."}
	}

	excludeDirSet := make(map[string]struct{})
	for _, d := range strings.Split(*excludeDirs, ",") {
		excludeDirSet[strings.TrimSpace(d)] = struct{}{}
	}

	excludeSuffixList := []string{}
	for _, s := range strings.Split(*excludeSuffix, ",") {
		excludeSuffixList = append(excludeSuffixList, strings.TrimSpace(s))
	}

	// Expand patterns using go list to get package directories.
	dirs, err := listPackageDirs(patterns, excludeDirSet)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error listing packages: %v\n", err)
		os.Exit(1)
	}

	// Collect all .go files from those directories.
	var files []string
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if !strings.HasSuffix(name, ".go") {
				continue
			}
			skip := false
			for _, suffix := range excludeSuffixList {
				if strings.HasSuffix(name, suffix) {
					skip = true
					break
				}
			}
			if !skip {
				files = append(files, filepath.Join(dir, name))
			}
		}
	}

	if *verbose {
		fmt.Printf("Scanning %d Go files...\n", len(files))
	}

	var violations []violation

	for _, path := range files {
		content, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "WARN: cannot read %s: %v\n", path, err)
			continue
		}

		// Skip generated files (look for "Code generated by" header).
		if strings.Contains(string(content), "Code generated by") {
			continue
		}

		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, content, parser.ParseComments)
		if err != nil {
			if *verbose {
				fmt.Fprintf(os.Stderr, "WARN: parse error in %s: %v\n", path, err)
			}
			continue
		}

		violations = append(violations, scanFile(fset, f, path)...)
	}

	if len(violations) == 0 {
		if *verbose {
			fmt.Println("No empty function bodies found.")
		}
		os.Exit(0)
	}

	fmt.Fprintf(os.Stderr, "ERROR: found %d empty function body(s):\n", len(violations))
	for _, v := range violations {
		fmt.Fprintf(os.Stderr, "  %s: %s %s — %s\n", v.pos, v.kind, v.name, v.reason)
	}
	os.Exit(1)
}

// listPackageDirs expands Go package patterns into a deduplicated list of
// package directory paths. Excludes directories matching excludeDirSet.
func listPackageDirs(patterns []string, excludeDirSet map[string]struct{}) ([]string, error) {
	args := append([]string{"list", "-f", "{{.Dir}}"}, patterns...)
	cmd := exec.Command("go", args...)
	cmd.Env = append(os.Environ(), "GOWORK=off")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	if err := cmd.Start(); err != nil {
		return nil, err
	}

	seen := make(map[string]struct{})
	var dirs []string
	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		dir := strings.TrimSpace(scanner.Text())
		if dir == "" {
			continue
		}
		// Skip directories inside excluded paths.
		skip := false
		for part := range excludeDirSet {
			if strings.Contains(dir, string(filepath.Separator)+part+string(filepath.Separator)) ||
				strings.HasSuffix(dir, string(filepath.Separator)+part) {
				skip = true
				break
			}
		}
		if skip {
			continue
		}
		// Skip fixtures directories (test fixtures for anti-bluff scanners).
		if strings.Contains(dir, string(filepath.Separator)+"fixtures"+string(filepath.Separator)) ||
			strings.HasSuffix(dir, string(filepath.Separator)+"fixtures") {
			continue
		}
		if _, ok := seen[dir]; !ok {
			seen[dir] = struct{}{}
			dirs = append(dirs, dir)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if err := cmd.Wait(); err != nil {
		if len(dirs) == 0 {
			return nil, err
		}
	}

	return dirs, nil
}

// scanFile walks the AST of a single file and returns all empty-body
// violations.
func scanFile(fset *token.FileSet, f *ast.File, filename string) []violation {
	var violations []violation

	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.FuncDecl:
			if isExcludedFunc(node.Name.Name) {
				return true
			}
			if node.Recv != nil && isExcludedType(receiverTypeName(node.Recv)) {
				return true
			}
			if node.Body == nil {
				// Interface method declaration — not a body.
				return true
			}
			reason := bodyEmptyReason(node.Body)
			if reason != "" {
				kind := "func"
				if node.Recv != nil {
					kind = "method"
				}
				name := node.Name.Name
				if node.Recv != nil {
					name = receiverTypeName(node.Recv) + "." + name
				}
				violations = append(violations, violation{
					pos:    fset.Position(node.Pos()),
					kind:   kind,
					name:   name,
					reason: reason,
				})
			}

		case *ast.FuncLit:
			reason := bodyEmptyReason(node.Body)
			if reason != "" {
				violations = append(violations, violation{
					pos:    fset.Position(node.Pos()),
					kind:   "func literal",
					name:   "<anonymous>",
					reason: reason,
				})
			}
		}
		return true
	})

	return violations
}

// bodyEmptyReason returns a non-empty string if the function body is
// considered "empty" for anti-bluff purposes.
func bodyEmptyReason(body *ast.BlockStmt) string {
	if body == nil {
		return ""
	}
	if len(body.List) == 0 {
		return "body contains zero statements"
	}
	return ""
}

// isExcludedFunc returns true for identifiers that are allowed to have
// empty bodies per Constitution §1.1.1.
func isExcludedFunc(name string) bool {
	upper := strings.ToUpper(name)
	if strings.Contains(upper, "NOOP") || strings.Contains(upper, "NO OP") {
		return true
	}
	// NopLogger, nopAdapter, etc. are conventional Go no-op names.
	if strings.HasPrefix(upper, "NOP") && !strings.Contains(upper, "SNAP") && !strings.Contains(upper, "CAN") {
		return true
	}
	if strings.Contains(upper, "MOCK") {
		return true
	}
	if strings.Contains(upper, "STUB") {
		return true
	}
	if name == "main" {
		return true
	}
	return false
}

// isExcludedType returns true for receiver type names that indicate the
// type is intentionally a no-op / stub / mock implementation.
func isExcludedType(typeName string) bool {
	upper := strings.ToUpper(typeName)
	if strings.Contains(upper, "NOOP") || strings.Contains(upper, "NO OP") {
		return true
	}
	// NopLogger, nopAdapter, etc. are conventional Go no-op names.
	if strings.HasPrefix(upper, "NOP") && !strings.Contains(upper, "SNAP") && !strings.Contains(upper, "CAN") {
		return true
	}
	if strings.Contains(upper, "MOCK") {
		return true
	}
	if strings.Contains(upper, "STUB") {
		return true
	}
	return false
}

// receiverTypeName extracts the type name from a receiver list for
// diagnostic output.
func receiverTypeName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	field := recv.List[0]
	expr := field.Type
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}
