// SPDX-FileCopyrightText: 2026 Milos Vasic
// SPDX-License-Identifier: Apache-2.0

// Mutation testing engine for Go.
//
// Constitution §6.4 requires a mutation score >= 85%. This tool
// performs AST-based mutation testing without external dependencies.
// It applies simple mutants to covered code, runs the test suite,
// and reports the mutation score.
//
// Supported mutants:
//   - CONDITIONALS_BOUNDARY: < → <=, > → >=, <= → <, >= → >
//   - CONDITIONALS_NEGATION: == → !=, != → ==
//   - INVERT_BOOLEAN: true → false, false → true
//   - ARITHMETIC_BASE: + → -, - → +, * → /, / → *
//
// Usage:
//   go run scripts/mutation_test.go ./pkg/models/...
//   go run scripts/mutation_test.go -threshold=0.85 ./cmd/core/...
//
// Exit code: 0 = score meets threshold, 1 = below threshold.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

var (
	threshold   = flag.Float64("threshold", 0.85, "minimum mutation score (0.0–1.0)")
	workers     = flag.Int("workers", 4, "concurrent mutation workers")
	excludeDirs = flag.String("exclude", "vendor,node_modules,dist,build,.git,fixtures", "comma-separated directory names to skip")
	verbose     = flag.Bool("v", false, "verbose output")
)

// mutant represents a single mutation.
type mutant struct {
	file    string
	pos     token.Position
	kind    string
	before  string
	after   string
	applied bool
}

func main() {
	flag.Parse()
	patterns := flag.Args()
	if len(patterns) == 0 {
		patterns = []string{"."}
	}

	excludeDirSet := make(map[string]struct{})
	for _, d := range strings.Split(*excludeDirs, ",") {
		excludeDirSet[strings.TrimSpace(d)] = struct{}{}
	}

	dirs, err := listPackageDirs(patterns, excludeDirSet)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error listing packages: %v\n", err)
		os.Exit(1)
	}

	var files []string
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
				continue
			}
			// Skip generated files.
			if strings.HasSuffix(name, ".pb.go") || name == "bindings.go" {
				continue
			}
			files = append(files, filepath.Join(dir, name))
		}
	}

	if *verbose {
		fmt.Printf("Scanning %d source files for mutants...\n", len(files))
	}

	// Collect all mutants.
	var mutants []mutant
	for _, path := range files {
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if strings.Contains(string(content), "Code generated by") {
			continue
		}
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, content, parser.ParseComments)
		if err != nil {
			continue
		}
		mutants = append(mutants, findMutants(fset, f, path, content)...)
	}

	if len(mutants) == 0 {
		fmt.Println("No mutants found.")
		os.Exit(0)
	}

	fmt.Printf("Found %d mutants. Testing...\n", len(mutants))

	// Run mutations concurrently.
	var killed, lived, skipped int
	var mu sync.Mutex

	sem := make(chan struct{}, *workers)
	var wg sync.WaitGroup

	for i := range mutants {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			m := &mutants[idx]
			result := testMutant(m)

			mu.Lock()
			switch result {
			case "killed":
				killed++
			case "lived":
				lived++
			case "skipped":
				skipped++
			}
			mu.Unlock()

			if *verbose {
				fmt.Printf("  [%s] %s:%d (%s) %s → %s\n", result, m.file, m.pos.Line, m.kind, m.before, m.after)
			}
		}(i)
	}

	wg.Wait()

	totalTested := killed + lived
	var score float64
	if totalTested > 0 {
		score = float64(killed) / float64(totalTested)
	}

	fmt.Printf("\nMutation Results:\n")
	fmt.Printf("  Total mutants:   %d\n", len(mutants))
	fmt.Printf("  Killed:          %d\n", killed)
	fmt.Printf("  Lived:           %d\n", lived)
	fmt.Printf("  Skipped:         %d (build/parse errors)\n", skipped)
	fmt.Printf("  Mutation score:  %.1f%% (threshold: %.0f%%)\n", score*100, *threshold*100)

	if totalTested == 0 {
		fmt.Fprintf(os.Stderr, "ERROR: no mutants could be tested\n")
		os.Exit(1)
	}

	if score < *threshold {
		fmt.Fprintf(os.Stderr, "ERROR: mutation score %.1f%% is below threshold %.0f%%\n",
			score*100, *threshold*100)
		os.Exit(1)
	}

	fmt.Println("PASS: mutation score meets threshold.")
}

// findMutants walks the AST and identifies mutation points.
func findMutants(fset *token.FileSet, f *ast.File, path string, content []byte) []mutant {
	var mutants []mutant
	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.BinaryExpr:
			if repl, ok := invertOperator(node.Op); ok {
				mutants = append(mutants, mutant{
					file:   path,
					pos:    fset.Position(node.Pos()),
					kind:   "conditionals_negation",
					before: node.Op.String(),
					after:  repl.String(),
				})
			}
			if repl, ok := boundaryOperator(node.Op); ok {
				mutants = append(mutants, mutant{
					file:   path,
					pos:    fset.Position(node.Pos()),
					kind:   "conditionals_boundary",
					before: node.Op.String(),
					after:  repl.String(),
				})
			}
			if repl, ok := arithmeticOperator(node.Op); ok {
				mutants = append(mutants, mutant{
					file:   path,
					pos:    fset.Position(node.Pos()),
					kind:   "arithmetic_base",
					before: node.Op.String(),
					after:  repl.String(),
				})
			}
		case *ast.Ident:
			if node.Name == "true" || node.Name == "false" {
				mutants = append(mutants, mutant{
					file:   path,
					pos:    fset.Position(node.Pos()),
					kind:   "invert_boolean",
					before: node.Name,
					after:  invertBool(node.Name),
				})
			}
		}
		return true
	})
	return mutants
}

// testMutant applies a single mutant, runs tests, and returns the outcome.
func testMutant(m *mutant) string {
	content, err := os.ReadFile(m.file)
	if err != nil {
		return "skipped"
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, m.file, content, parser.ParseComments)
	if err != nil {
		return "skipped"
	}

	// Apply mutation.
	mutated := applyMutation(fset, f, m)
	if mutated == nil {
		return "skipped"
	}

	// Write mutated file.
	var buf strings.Builder
	if err := format.Node(&buf, fset, mutated); err != nil {
		return "skipped"
	}
	mutatedContent := buf.String()

	if err := os.WriteFile(m.file, []byte(mutatedContent), 0644); err != nil {
		return "skipped"
	}

	// Run tests in the file's directory.
	dir := filepath.Dir(m.file)
	cmd := exec.Command("go", "test", "-count=1", "-timeout=30s", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()

	// Restore original file.
	_ = os.WriteFile(m.file, content, 0644)

	if err != nil {
		// Tests failed → mutant was killed.
		return "killed"
	}

	// Tests passed → mutant survived.
	if strings.Contains(string(out), "no test files") || strings.Contains(string(out), "no tests to run") {
		return "skipped"
	}
	return "lived"
}

// applyMutation applies the mutant to the AST and returns the modified file.
func applyMutation(fset *token.FileSet, f *ast.File, m *mutant) *ast.File {
	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.BinaryExpr:
			pos := fset.Position(node.Pos())
			if pos.Line == m.pos.Line && node.Op.String() == m.before {
				node.Op = tokenFromString(m.after)
				return false
			}
		case *ast.Ident:
			pos := fset.Position(node.Pos())
			if pos.Line == m.pos.Line && node.Name == m.before {
				node.Name = m.after
				return false
			}
		}
		return true
	})
	return f
}

// invertOperator maps equality/inequality operators to their inverses.
func invertOperator(op token.Token) (token.Token, bool) {
	switch op {
	case token.EQL:
		return token.NEQ, true
	case token.NEQ:
		return token.EQL, true
	}
	return token.ILLEGAL, false
}

// boundaryOperator maps comparison operators to their boundary-shifted versions.
func boundaryOperator(op token.Token) (token.Token, bool) {
	switch op {
	case token.LSS:
		return token.LEQ, true
	case token.GTR:
		return token.GEQ, true
	case token.LEQ:
		return token.LSS, true
	case token.GEQ:
		return token.GTR, true
	}
	return token.ILLEGAL, false
}

// arithmeticOperator maps arithmetic operators to alternative operators.
func arithmeticOperator(op token.Token) (token.Token, bool) {
	switch op {
	case token.ADD:
		return token.SUB, true
	case token.SUB:
		return token.ADD, true
	case token.MUL:
		return token.QUO, true
	case token.QUO:
		return token.MUL, true
	}
	return token.ILLEGAL, false
}

func invertBool(s string) string {
	if s == "true" {
		return "false"
	}
	return "true"
}

func tokenFromString(s string) token.Token {
	switch s {
	case "==":
		return token.EQL
	case "!=":
		return token.NEQ
	case "<":
		return token.LSS
	case ">":
		return token.GTR
	case "<=":
		return token.LEQ
	case ">=":
		return token.GEQ
	case "+":
		return token.ADD
	case "-":
		return token.SUB
	case "*":
		return token.MUL
	case "/":
		return token.QUO
	}
	return token.ILLEGAL
}

// listPackageDirs expands Go package patterns into a deduplicated list of
// package directory paths. Excludes directories matching excludeDirSet.
func listPackageDirs(patterns []string, excludeDirSet map[string]struct{}) ([]string, error) {
	args := append([]string{"list", "-f", "{{.Dir}}"}, patterns...)
	cmd := exec.Command("go", args...)
	cmd.Env = append(os.Environ(), "GOWORK=off")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	if err := cmd.Start(); err != nil {
		return nil, err
	}

	seen := make(map[string]struct{})
	var dirs []string
	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		dir := strings.TrimSpace(scanner.Text())
		if dir == "" {
			continue
		}
		skip := false
		for part := range excludeDirSet {
			if strings.Contains(dir, string(filepath.Separator)+part+string(filepath.Separator)) ||
				strings.HasSuffix(dir, string(filepath.Separator)+part) {
				skip = true
				break
			}
		}
		if skip {
			continue
		}
		if _, ok := seen[dir]; !ok {
			seen[dir] = struct{}{}
			dirs = append(dirs, dir)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if err := cmd.Wait(); err != nil {
		if len(dirs) == 0 {
			return nil, err
		}
	}

	return dirs, nil
}
