// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.5
// source: streaming.proto

package streamingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingControl_NegotiateStream_FullMethodName      = "/streaming.v1.StreamingControl/NegotiateStream"
	StreamingControl_PushTelemetry_FullMethodName        = "/streaming.v1.StreamingControl/PushTelemetry"
	StreamingControl_StreamQualityUpdates_FullMethodName = "/streaming.v1.StreamingControl/StreamQualityUpdates"
	StreamingControl_Health_FullMethodName               = "/streaming.v1.StreamingControl/Health"
)

// StreamingControlClient is the client API for StreamingControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StreamingControl manages capability negotiation and session lifecycle
type StreamingControlClient interface {
	// Bidirectional capability negotiation
	NegotiateStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NegotiateMessage, NegotiateMessage], error)
	// Client telemetry push for ABR/congestion control
	PushTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryPacket, TelemetryAck], error)
	// Host quality-of-stream updates
	StreamQualityUpdates(ctx context.Context, in *StreamQualityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QualityUpdate], error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type streamingControlClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingControlClient(cc grpc.ClientConnInterface) StreamingControlClient {
	return &streamingControlClient{cc}
}

func (c *streamingControlClient) NegotiateStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NegotiateMessage, NegotiateMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingControl_ServiceDesc.Streams[0], StreamingControl_NegotiateStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NegotiateMessage, NegotiateMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingControl_NegotiateStreamClient = grpc.BidiStreamingClient[NegotiateMessage, NegotiateMessage]

func (c *streamingControlClient) PushTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryPacket, TelemetryAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingControl_ServiceDesc.Streams[1], StreamingControl_PushTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryPacket, TelemetryAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingControl_PushTelemetryClient = grpc.ClientStreamingClient[TelemetryPacket, TelemetryAck]

func (c *streamingControlClient) StreamQualityUpdates(ctx context.Context, in *StreamQualityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QualityUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingControl_ServiceDesc.Streams[2], StreamingControl_StreamQualityUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamQualityRequest, QualityUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingControl_StreamQualityUpdatesClient = grpc.ServerStreamingClient[QualityUpdate]

func (c *streamingControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, StreamingControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingControlServer is the server API for StreamingControl service.
// All implementations must embed UnimplementedStreamingControlServer
// for forward compatibility.
//
// StreamingControl manages capability negotiation and session lifecycle
type StreamingControlServer interface {
	// Bidirectional capability negotiation
	NegotiateStream(grpc.BidiStreamingServer[NegotiateMessage, NegotiateMessage]) error
	// Client telemetry push for ABR/congestion control
	PushTelemetry(grpc.ClientStreamingServer[TelemetryPacket, TelemetryAck]) error
	// Host quality-of-stream updates
	StreamQualityUpdates(*StreamQualityRequest, grpc.ServerStreamingServer[QualityUpdate]) error
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedStreamingControlServer()
}

// UnimplementedStreamingControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingControlServer struct{}

func (UnimplementedStreamingControlServer) NegotiateStream(grpc.BidiStreamingServer[NegotiateMessage, NegotiateMessage]) error {
	return status.Error(codes.Unimplemented, "method NegotiateStream not implemented")
}
func (UnimplementedStreamingControlServer) PushTelemetry(grpc.ClientStreamingServer[TelemetryPacket, TelemetryAck]) error {
	return status.Error(codes.Unimplemented, "method PushTelemetry not implemented")
}
func (UnimplementedStreamingControlServer) StreamQualityUpdates(*StreamQualityRequest, grpc.ServerStreamingServer[QualityUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamQualityUpdates not implemented")
}
func (UnimplementedStreamingControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedStreamingControlServer) mustEmbedUnimplementedStreamingControlServer() {}
func (UnimplementedStreamingControlServer) testEmbeddedByValue()                          {}

// UnsafeStreamingControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingControlServer will
// result in compilation errors.
type UnsafeStreamingControlServer interface {
	mustEmbedUnimplementedStreamingControlServer()
}

func RegisterStreamingControlServer(s grpc.ServiceRegistrar, srv StreamingControlServer) {
	// If the following call panics, it indicates UnimplementedStreamingControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingControl_ServiceDesc, srv)
}

func _StreamingControl_NegotiateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingControlServer).NegotiateStream(&grpc.GenericServerStream[NegotiateMessage, NegotiateMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingControl_NegotiateStreamServer = grpc.BidiStreamingServer[NegotiateMessage, NegotiateMessage]

func _StreamingControl_PushTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingControlServer).PushTelemetry(&grpc.GenericServerStream[TelemetryPacket, TelemetryAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingControl_PushTelemetryServer = grpc.ClientStreamingServer[TelemetryPacket, TelemetryAck]

func _StreamingControl_StreamQualityUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamQualityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingControlServer).StreamQualityUpdates(m, &grpc.GenericServerStream[StreamQualityRequest, QualityUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingControl_StreamQualityUpdatesServer = grpc.ServerStreamingServer[QualityUpdate]

func _StreamingControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamingControl_ServiceDesc is the grpc.ServiceDesc for StreamingControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.v1.StreamingControl",
	HandlerType: (*StreamingControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _StreamingControl_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NegotiateStream",
			Handler:       _StreamingControl_NegotiateStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushTelemetry",
			Handler:       _StreamingControl_PushTelemetry_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamQualityUpdates",
			Handler:       _StreamingControl_StreamQualityUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
