// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: streaming.proto

package streamingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NegotiateMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NegotiateMessage_ClientHello
	//	*NegotiateMessage_HostAdvertisement
	//	*NegotiateMessage_ClientOffer
	//	*NegotiateMessage_HostAnswer
	//	*NegotiateMessage_IceCandidate
	//	*NegotiateMessage_Ready
	//	*NegotiateMessage_Renegotiate
	//	*NegotiateMessage_Terminate
	//	*NegotiateMessage_Error
	Payload       isNegotiateMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegotiateMessage) Reset() {
	*x = NegotiateMessage{}
	mi := &file_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiateMessage) ProtoMessage() {}

func (x *NegotiateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiateMessage.ProtoReflect.Descriptor instead.
func (*NegotiateMessage) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *NegotiateMessage) GetPayload() isNegotiateMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NegotiateMessage) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *NegotiateMessage) GetHostAdvertisement() *HostAdvertisement {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_HostAdvertisement); ok {
			return x.HostAdvertisement
		}
	}
	return nil
}

func (x *NegotiateMessage) GetClientOffer() *ClientOffer {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_ClientOffer); ok {
			return x.ClientOffer
		}
	}
	return nil
}

func (x *NegotiateMessage) GetHostAnswer() *HostAnswer {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_HostAnswer); ok {
			return x.HostAnswer
		}
	}
	return nil
}

func (x *NegotiateMessage) GetIceCandidate() *ICECandidate {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_IceCandidate); ok {
			return x.IceCandidate
		}
	}
	return nil
}

func (x *NegotiateMessage) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *NegotiateMessage) GetRenegotiate() *Renegotiate {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_Renegotiate); ok {
			return x.Renegotiate
		}
	}
	return nil
}

func (x *NegotiateMessage) GetTerminate() *Terminate {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_Terminate); ok {
			return x.Terminate
		}
	}
	return nil
}

func (x *NegotiateMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*NegotiateMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isNegotiateMessage_Payload interface {
	isNegotiateMessage_Payload()
}

type NegotiateMessage_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type NegotiateMessage_HostAdvertisement struct {
	HostAdvertisement *HostAdvertisement `protobuf:"bytes,2,opt,name=host_advertisement,json=hostAdvertisement,proto3,oneof"`
}

type NegotiateMessage_ClientOffer struct {
	ClientOffer *ClientOffer `protobuf:"bytes,3,opt,name=client_offer,json=clientOffer,proto3,oneof"`
}

type NegotiateMessage_HostAnswer struct {
	HostAnswer *HostAnswer `protobuf:"bytes,4,opt,name=host_answer,json=hostAnswer,proto3,oneof"`
}

type NegotiateMessage_IceCandidate struct {
	IceCandidate *ICECandidate `protobuf:"bytes,5,opt,name=ice_candidate,json=iceCandidate,proto3,oneof"`
}

type NegotiateMessage_Ready struct {
	Ready *Ready `protobuf:"bytes,6,opt,name=ready,proto3,oneof"`
}

type NegotiateMessage_Renegotiate struct {
	Renegotiate *Renegotiate `protobuf:"bytes,7,opt,name=renegotiate,proto3,oneof"`
}

type NegotiateMessage_Terminate struct {
	Terminate *Terminate `protobuf:"bytes,8,opt,name=terminate,proto3,oneof"`
}

type NegotiateMessage_Error struct {
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*NegotiateMessage_ClientHello) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_HostAdvertisement) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_ClientOffer) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_HostAnswer) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_IceCandidate) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_Ready) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_Renegotiate) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_Terminate) isNegotiateMessage_Payload() {}

func (*NegotiateMessage_Error) isNegotiateMessage_Payload() {}

type ClientHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthToken       string                 `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	RequestedGameId string                 `protobuf:"bytes,5,opt,name=requested_game_id,json=requestedGameId,proto3" json:"requested_game_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHello) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientHello) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *ClientHello) GetRequestedGameId() string {
	if x != nil {
		return x.RequestedGameId
	}
	return ""
}

type HostAdvertisement struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HostId             string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	GpuEntries         []*GPUEntry            `protobuf:"bytes,2,rep,name=gpu_entries,json=gpuEntries,proto3" json:"gpu_entries,omitempty"`
	Codecs             []string               `protobuf:"bytes,3,rep,name=codecs,proto3" json:"codecs,omitempty"`
	Transports         []string               `protobuf:"bytes,4,rep,name=transports,proto3" json:"transports,omitempty"`
	MaxResolution      *Resolution            `protobuf:"bytes,5,opt,name=max_resolution,json=maxResolution,proto3" json:"max_resolution,omitempty"`
	MaxRefreshRate     int32                  `protobuf:"varint,6,opt,name=max_refresh_rate,json=maxRefreshRate,proto3" json:"max_refresh_rate,omitempty"`
	HdrFormats         []string               `protobuf:"bytes,7,rep,name=hdr_formats,json=hdrFormats,proto3" json:"hdr_formats,omitempty"`
	ThermalHeadroomPct int32                  `protobuf:"varint,8,opt,name=thermal_headroom_pct,json=thermalHeadroomPct,proto3" json:"thermal_headroom_pct,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HostAdvertisement) Reset() {
	*x = HostAdvertisement{}
	mi := &file_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAdvertisement) ProtoMessage() {}

func (x *HostAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAdvertisement.ProtoReflect.Descriptor instead.
func (*HostAdvertisement) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *HostAdvertisement) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostAdvertisement) GetGpuEntries() []*GPUEntry {
	if x != nil {
		return x.GpuEntries
	}
	return nil
}

func (x *HostAdvertisement) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *HostAdvertisement) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *HostAdvertisement) GetMaxResolution() *Resolution {
	if x != nil {
		return x.MaxResolution
	}
	return nil
}

func (x *HostAdvertisement) GetMaxRefreshRate() int32 {
	if x != nil {
		return x.MaxRefreshRate
	}
	return 0
}

func (x *HostAdvertisement) GetHdrFormats() []string {
	if x != nil {
		return x.HdrFormats
	}
	return nil
}

func (x *HostAdvertisement) GetThermalHeadroomPct() int32 {
	if x != nil {
		return x.ThermalHeadroomPct
	}
	return 0
}

type GPUEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Encoder       string                 `protobuf:"bytes,4,opt,name=encoder,proto3" json:"encoder,omitempty"`
	Codecs        []string               `protobuf:"bytes,5,rep,name=codecs,proto3" json:"codecs,omitempty"`
	VramGb        int32                  `protobuf:"varint,6,opt,name=vram_gb,json=vramGb,proto3" json:"vram_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUEntry) Reset() {
	*x = GPUEntry{}
	mi := &file_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUEntry) ProtoMessage() {}

func (x *GPUEntry) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUEntry.ProtoReflect.Descriptor instead.
func (*GPUEntry) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *GPUEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUEntry) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUEntry) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUEntry) GetEncoder() string {
	if x != nil {
		return x.Encoder
	}
	return ""
}

func (x *GPUEntry) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *GPUEntry) GetVramGb() int32 {
	if x != nil {
		return x.VramGb
	}
	return 0
}

type ClientOffer struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PreferredCodec     string                 `protobuf:"bytes,1,opt,name=preferred_codec,json=preferredCodec,proto3" json:"preferred_codec,omitempty"`
	FallbackCodecs     []string               `protobuf:"bytes,2,rep,name=fallback_codecs,json=fallbackCodecs,proto3" json:"fallback_codecs,omitempty"`
	PreferredTransport string                 `protobuf:"bytes,3,opt,name=preferred_transport,json=preferredTransport,proto3" json:"preferred_transport,omitempty"`
	DisplayCaps        *DisplayCaps           `protobuf:"bytes,4,opt,name=display_caps,json=displayCaps,proto3" json:"display_caps,omitempty"`
	DecoderCaps        *DecoderCaps           `protobuf:"bytes,5,opt,name=decoder_caps,json=decoderCaps,proto3" json:"decoder_caps,omitempty"`
	NetworkCaps        *NetworkCaps           `protobuf:"bytes,6,opt,name=network_caps,json=networkCaps,proto3" json:"network_caps,omitempty"`
	AudioCaps          *AudioCaps             `protobuf:"bytes,7,opt,name=audio_caps,json=audioCaps,proto3" json:"audio_caps,omitempty"`
	ControllerCaps     *ControllerCaps        `protobuf:"bytes,8,opt,name=controller_caps,json=controllerCaps,proto3" json:"controller_caps,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientOffer) Reset() {
	*x = ClientOffer{}
	mi := &file_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOffer) ProtoMessage() {}

func (x *ClientOffer) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOffer.ProtoReflect.Descriptor instead.
func (*ClientOffer) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *ClientOffer) GetPreferredCodec() string {
	if x != nil {
		return x.PreferredCodec
	}
	return ""
}

func (x *ClientOffer) GetFallbackCodecs() []string {
	if x != nil {
		return x.FallbackCodecs
	}
	return nil
}

func (x *ClientOffer) GetPreferredTransport() string {
	if x != nil {
		return x.PreferredTransport
	}
	return ""
}

func (x *ClientOffer) GetDisplayCaps() *DisplayCaps {
	if x != nil {
		return x.DisplayCaps
	}
	return nil
}

func (x *ClientOffer) GetDecoderCaps() *DecoderCaps {
	if x != nil {
		return x.DecoderCaps
	}
	return nil
}

func (x *ClientOffer) GetNetworkCaps() *NetworkCaps {
	if x != nil {
		return x.NetworkCaps
	}
	return nil
}

func (x *ClientOffer) GetAudioCaps() *AudioCaps {
	if x != nil {
		return x.AudioCaps
	}
	return nil
}

func (x *ClientOffer) GetControllerCaps() *ControllerCaps {
	if x != nil {
		return x.ControllerCaps
	}
	return nil
}

type HostAnswer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SelectedCodec     string                 `protobuf:"bytes,1,opt,name=selected_codec,json=selectedCodec,proto3" json:"selected_codec,omitempty"`
	SelectedTransport string                 `protobuf:"bytes,2,opt,name=selected_transport,json=selectedTransport,proto3" json:"selected_transport,omitempty"`
	SelectedGpuIndex  int32                  `protobuf:"varint,3,opt,name=selected_gpu_index,json=selectedGpuIndex,proto3" json:"selected_gpu_index,omitempty"`
	Resolution        *Resolution            `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	RefreshRate       int32                  `protobuf:"varint,5,opt,name=refresh_rate,json=refreshRate,proto3" json:"refresh_rate,omitempty"`
	BitrateTargetKbps int32                  `protobuf:"varint,6,opt,name=bitrate_target_kbps,json=bitrateTargetKbps,proto3" json:"bitrate_target_kbps,omitempty"`
	HdrMode           string                 `protobuf:"bytes,7,opt,name=hdr_mode,json=hdrMode,proto3" json:"hdr_mode,omitempty"`
	SrtpParameters    *SRTPParams            `protobuf:"bytes,8,opt,name=srtp_parameters,json=srtpParameters,proto3" json:"srtp_parameters,omitempty"`
	QuicConfig        *QUICConfig            `protobuf:"bytes,9,opt,name=quic_config,json=quicConfig,proto3" json:"quic_config,omitempty"`
	UdpConfig         *UDPConfig             `protobuf:"bytes,10,opt,name=udp_config,json=udpConfig,proto3" json:"udp_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostAnswer) Reset() {
	*x = HostAnswer{}
	mi := &file_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAnswer) ProtoMessage() {}

func (x *HostAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAnswer.ProtoReflect.Descriptor instead.
func (*HostAnswer) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *HostAnswer) GetSelectedCodec() string {
	if x != nil {
		return x.SelectedCodec
	}
	return ""
}

func (x *HostAnswer) GetSelectedTransport() string {
	if x != nil {
		return x.SelectedTransport
	}
	return ""
}

func (x *HostAnswer) GetSelectedGpuIndex() int32 {
	if x != nil {
		return x.SelectedGpuIndex
	}
	return 0
}

func (x *HostAnswer) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *HostAnswer) GetRefreshRate() int32 {
	if x != nil {
		return x.RefreshRate
	}
	return 0
}

func (x *HostAnswer) GetBitrateTargetKbps() int32 {
	if x != nil {
		return x.BitrateTargetKbps
	}
	return 0
}

func (x *HostAnswer) GetHdrMode() string {
	if x != nil {
		return x.HdrMode
	}
	return ""
}

func (x *HostAnswer) GetSrtpParameters() *SRTPParams {
	if x != nil {
		return x.SrtpParameters
	}
	return nil
}

func (x *HostAnswer) GetQuicConfig() *QUICConfig {
	if x != nil {
		return x.QuicConfig
	}
	return nil
}

func (x *HostAnswer) GetUdpConfig() *UDPConfig {
	if x != nil {
		return x.UdpConfig
	}
	return nil
}

type ICECandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SdpMid        string                 `protobuf:"bytes,1,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,2,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	Candidate     string                 `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidate) Reset() {
	*x = ICECandidate{}
	mi := &file_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidate) ProtoMessage() {}

func (x *ICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidate.ProtoReflect.Descriptor instead.
func (*ICECandidate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *ICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *ICECandidate) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *ICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ssrc          int32                  `protobuf:"varint,2,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	PayloadType   int32                  `protobuf:"varint,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *Ready) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Ready) GetSsrc() int32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *Ready) GetPayloadType() int32 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

type Renegotiate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	NewOffer      *ClientOffer           `protobuf:"bytes,2,opt,name=new_offer,json=newOffer,proto3" json:"new_offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Renegotiate) Reset() {
	*x = Renegotiate{}
	mi := &file_streaming_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Renegotiate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renegotiate) ProtoMessage() {}

func (x *Renegotiate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renegotiate.ProtoReflect.Descriptor instead.
func (*Renegotiate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{8}
}

func (x *Renegotiate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Renegotiate) GetNewOffer() *ClientOffer {
	if x != nil {
		return x.NewOffer
	}
	return nil
}

type Terminate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Terminate) Reset() {
	*x = Terminate{}
	mi := &file_streaming_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminate) ProtoMessage() {}

func (x *Terminate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminate.ProtoReflect.Descriptor instead.
func (*Terminate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{9}
}

func (x *Terminate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_streaming_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_streaming_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{11}
}

func (x *Resolution) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resolution) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type DisplayCaps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	RefreshHz     int32                  `protobuf:"varint,3,opt,name=refresh_hz,json=refreshHz,proto3" json:"refresh_hz,omitempty"`
	HdrSupported  bool                   `protobuf:"varint,4,opt,name=hdr_supported,json=hdrSupported,proto3" json:"hdr_supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayCaps) Reset() {
	*x = DisplayCaps{}
	mi := &file_streaming_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayCaps) ProtoMessage() {}

func (x *DisplayCaps) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayCaps.ProtoReflect.Descriptor instead.
func (*DisplayCaps) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{12}
}

func (x *DisplayCaps) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DisplayCaps) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DisplayCaps) GetRefreshHz() int32 {
	if x != nil {
		return x.RefreshHz
	}
	return 0
}

func (x *DisplayCaps) GetHdrSupported() bool {
	if x != nil {
		return x.HdrSupported
	}
	return false
}

type DecoderCaps struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HardwareDecoders      []string               `protobuf:"bytes,1,rep,name=hardware_decoders,json=hardwareDecoders,proto3" json:"hardware_decoders,omitempty"`
	MaxResolutionPerCodec map[string]*Resolution `protobuf:"bytes,2,rep,name=max_resolution_per_codec,json=maxResolutionPerCodec,proto3" json:"max_resolution_per_codec,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DecoderCaps) Reset() {
	*x = DecoderCaps{}
	mi := &file_streaming_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecoderCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoderCaps) ProtoMessage() {}

func (x *DecoderCaps) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoderCaps.ProtoReflect.Descriptor instead.
func (*DecoderCaps) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{13}
}

func (x *DecoderCaps) GetHardwareDecoders() []string {
	if x != nil {
		return x.HardwareDecoders
	}
	return nil
}

func (x *DecoderCaps) GetMaxResolutionPerCodec() map[string]*Resolution {
	if x != nil {
		return x.MaxResolutionPerCodec
	}
	return nil
}

type NetworkCaps struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxBandwidthMbps int32                  `protobuf:"varint,1,opt,name=max_bandwidth_mbps,json=maxBandwidthMbps,proto3" json:"max_bandwidth_mbps,omitempty"`
	SupportsBbr      bool                   `protobuf:"varint,2,opt,name=supports_bbr,json=supportsBbr,proto3" json:"supports_bbr,omitempty"`
	RttMsEstimate    int32                  `protobuf:"varint,3,opt,name=rtt_ms_estimate,json=rttMsEstimate,proto3" json:"rtt_ms_estimate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkCaps) Reset() {
	*x = NetworkCaps{}
	mi := &file_streaming_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCaps) ProtoMessage() {}

func (x *NetworkCaps) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCaps.ProtoReflect.Descriptor instead.
func (*NetworkCaps) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{14}
}

func (x *NetworkCaps) GetMaxBandwidthMbps() int32 {
	if x != nil {
		return x.MaxBandwidthMbps
	}
	return 0
}

func (x *NetworkCaps) GetSupportsBbr() bool {
	if x != nil {
		return x.SupportsBbr
	}
	return false
}

func (x *NetworkCaps) GetRttMsEstimate() int32 {
	if x != nil {
		return x.RttMsEstimate
	}
	return 0
}

type AudioCaps struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Codecs               []string               `protobuf:"bytes,1,rep,name=codecs,proto3" json:"codecs,omitempty"`
	MaxChannels          int32                  `protobuf:"varint,2,opt,name=max_channels,json=maxChannels,proto3" json:"max_channels,omitempty"`
	PreferredBitrateKbps int32                  `protobuf:"varint,3,opt,name=preferred_bitrate_kbps,json=preferredBitrateKbps,proto3" json:"preferred_bitrate_kbps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AudioCaps) Reset() {
	*x = AudioCaps{}
	mi := &file_streaming_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioCaps) ProtoMessage() {}

func (x *AudioCaps) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioCaps.ProtoReflect.Descriptor instead.
func (*AudioCaps) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{15}
}

func (x *AudioCaps) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *AudioCaps) GetMaxChannels() int32 {
	if x != nil {
		return x.MaxChannels
	}
	return 0
}

func (x *AudioCaps) GetPreferredBitrateKbps() int32 {
	if x != nil {
		return x.PreferredBitrateKbps
	}
	return 0
}

type ControllerCaps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Haptic        bool                   `protobuf:"varint,2,opt,name=haptic,proto3" json:"haptic,omitempty"`
	Trigger       bool                   `protobuf:"varint,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Gyro          bool                   `protobuf:"varint,4,opt,name=gyro,proto3" json:"gyro,omitempty"`
	AudioJack     bool                   `protobuf:"varint,5,opt,name=audio_jack,json=audioJack,proto3" json:"audio_jack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerCaps) Reset() {
	*x = ControllerCaps{}
	mi := &file_streaming_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerCaps) ProtoMessage() {}

func (x *ControllerCaps) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerCaps.ProtoReflect.Descriptor instead.
func (*ControllerCaps) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{16}
}

func (x *ControllerCaps) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ControllerCaps) GetHaptic() bool {
	if x != nil {
		return x.Haptic
	}
	return false
}

func (x *ControllerCaps) GetTrigger() bool {
	if x != nil {
		return x.Trigger
	}
	return false
}

func (x *ControllerCaps) GetGyro() bool {
	if x != nil {
		return x.Gyro
	}
	return false
}

func (x *ControllerCaps) GetAudioJack() bool {
	if x != nil {
		return x.AudioJack
	}
	return false
}

type SRTPParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Salt          []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRTPParams) Reset() {
	*x = SRTPParams{}
	mi := &file_streaming_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRTPParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRTPParams) ProtoMessage() {}

func (x *SRTPParams) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRTPParams.ProtoReflect.Descriptor instead.
func (*SRTPParams) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{17}
}

func (x *SRTPParams) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SRTPParams) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type QUICConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alpn          string                 `protobuf:"bytes,1,opt,name=alpn,proto3" json:"alpn,omitempty"`
	ZeroRttToken  []byte                 `protobuf:"bytes,2,opt,name=zero_rtt_token,json=zeroRttToken,proto3" json:"zero_rtt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QUICConfig) Reset() {
	*x = QUICConfig{}
	mi := &file_streaming_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QUICConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QUICConfig) ProtoMessage() {}

func (x *QUICConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QUICConfig.ProtoReflect.Descriptor instead.
func (*QUICConfig) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{18}
}

func (x *QUICConfig) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *QUICConfig) GetZeroRttToken() []byte {
	if x != nil {
		return x.ZeroRttToken
	}
	return nil
}

type UDPConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DtlsFingerprint string                 `protobuf:"bytes,1,opt,name=dtls_fingerprint,json=dtlsFingerprint,proto3" json:"dtls_fingerprint,omitempty"`
	Port            int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UDPConfig) Reset() {
	*x = UDPConfig{}
	mi := &file_streaming_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPConfig) ProtoMessage() {}

func (x *UDPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPConfig.ProtoReflect.Descriptor instead.
func (*UDPConfig) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{19}
}

func (x *UDPConfig) GetDtlsFingerprint() string {
	if x != nil {
		return x.DtlsFingerprint
	}
	return ""
}

func (x *UDPConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TelemetryPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Video         *VideoTelemetry        `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	Network       *NetworkTelemetry      `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Input         *InputTelemetry        `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Display       *DisplayTelemetry      `protobuf:"bytes,6,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPacket) Reset() {
	*x = TelemetryPacket{}
	mi := &file_streaming_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPacket) ProtoMessage() {}

func (x *TelemetryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPacket.ProtoReflect.Descriptor instead.
func (*TelemetryPacket) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{20}
}

func (x *TelemetryPacket) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TelemetryPacket) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TelemetryPacket) GetVideo() *VideoTelemetry {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *TelemetryPacket) GetNetwork() *NetworkTelemetry {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *TelemetryPacket) GetInput() *InputTelemetry {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TelemetryPacket) GetDisplay() *DisplayTelemetry {
	if x != nil {
		return x.Display
	}
	return nil
}

type VideoTelemetry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FramesReceived int32                  `protobuf:"varint,1,opt,name=frames_received,json=framesReceived,proto3" json:"frames_received,omitempty"`
	FramesDecoded  int32                  `protobuf:"varint,2,opt,name=frames_decoded,json=framesDecoded,proto3" json:"frames_decoded,omitempty"`
	FramesDropped  int32                  `protobuf:"varint,3,opt,name=frames_dropped,json=framesDropped,proto3" json:"frames_dropped,omitempty"`
	DecodeTimeMs   float32                `protobuf:"fixed32,4,opt,name=decode_time_ms,json=decodeTimeMs,proto3" json:"decode_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoTelemetry) Reset() {
	*x = VideoTelemetry{}
	mi := &file_streaming_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTelemetry) ProtoMessage() {}

func (x *VideoTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTelemetry.ProtoReflect.Descriptor instead.
func (*VideoTelemetry) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{21}
}

func (x *VideoTelemetry) GetFramesReceived() int32 {
	if x != nil {
		return x.FramesReceived
	}
	return 0
}

func (x *VideoTelemetry) GetFramesDecoded() int32 {
	if x != nil {
		return x.FramesDecoded
	}
	return 0
}

func (x *VideoTelemetry) GetFramesDropped() int32 {
	if x != nil {
		return x.FramesDropped
	}
	return 0
}

func (x *VideoTelemetry) GetDecodeTimeMs() float32 {
	if x != nil {
		return x.DecodeTimeMs
	}
	return 0
}

type NetworkTelemetry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BandwidthEstimateMbps float32                `protobuf:"fixed32,1,opt,name=bandwidth_estimate_mbps,json=bandwidthEstimateMbps,proto3" json:"bandwidth_estimate_mbps,omitempty"`
	RttMs                 float32                `protobuf:"fixed32,2,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	JitterMs              float32                `protobuf:"fixed32,3,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	PacketLossPct         float32                `protobuf:"fixed32,4,opt,name=packet_loss_pct,json=packetLossPct,proto3" json:"packet_loss_pct,omitempty"`
	FecRecoveries         int32                  `protobuf:"varint,5,opt,name=fec_recoveries,json=fecRecoveries,proto3" json:"fec_recoveries,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NetworkTelemetry) Reset() {
	*x = NetworkTelemetry{}
	mi := &file_streaming_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTelemetry) ProtoMessage() {}

func (x *NetworkTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTelemetry.ProtoReflect.Descriptor instead.
func (*NetworkTelemetry) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{22}
}

func (x *NetworkTelemetry) GetBandwidthEstimateMbps() float32 {
	if x != nil {
		return x.BandwidthEstimateMbps
	}
	return 0
}

func (x *NetworkTelemetry) GetRttMs() float32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *NetworkTelemetry) GetJitterMs() float32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *NetworkTelemetry) GetPacketLossPct() float32 {
	if x != nil {
		return x.PacketLossPct
	}
	return 0
}

func (x *NetworkTelemetry) GetFecRecoveries() int32 {
	if x != nil {
		return x.FecRecoveries
	}
	return 0
}

type InputTelemetry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ControllerEvents int32                  `protobuf:"varint,1,opt,name=controller_events,json=controllerEvents,proto3" json:"controller_events,omitempty"`
	LatencyUsAvg     float32                `protobuf:"fixed32,2,opt,name=latency_us_avg,json=latencyUsAvg,proto3" json:"latency_us_avg,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InputTelemetry) Reset() {
	*x = InputTelemetry{}
	mi := &file_streaming_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputTelemetry) ProtoMessage() {}

func (x *InputTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputTelemetry.ProtoReflect.Descriptor instead.
func (*InputTelemetry) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{23}
}

func (x *InputTelemetry) GetControllerEvents() int32 {
	if x != nil {
		return x.ControllerEvents
	}
	return 0
}

func (x *InputTelemetry) GetLatencyUsAvg() float32 {
	if x != nil {
		return x.LatencyUsAvg
	}
	return 0
}

type DisplayTelemetry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActualHz          float32                `protobuf:"fixed32,1,opt,name=actual_hz,json=actualHz,proto3" json:"actual_hz,omitempty"`
	VsyncOffsetMs     float32                `protobuf:"fixed32,2,opt,name=vsync_offset_ms,json=vsyncOffsetMs,proto3" json:"vsync_offset_ms,omitempty"`
	DisplayQueueDepth int32                  `protobuf:"varint,3,opt,name=display_queue_depth,json=displayQueueDepth,proto3" json:"display_queue_depth,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DisplayTelemetry) Reset() {
	*x = DisplayTelemetry{}
	mi := &file_streaming_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayTelemetry) ProtoMessage() {}

func (x *DisplayTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayTelemetry.ProtoReflect.Descriptor instead.
func (*DisplayTelemetry) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{24}
}

func (x *DisplayTelemetry) GetActualHz() float32 {
	if x != nil {
		return x.ActualHz
	}
	return 0
}

func (x *DisplayTelemetry) GetVsyncOffsetMs() float32 {
	if x != nil {
		return x.VsyncOffsetMs
	}
	return 0
}

func (x *DisplayTelemetry) GetDisplayQueueDepth() int32 {
	if x != nil {
		return x.DisplayQueueDepth
	}
	return 0
}

type TelemetryAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AckSequence       int64                  `protobuf:"varint,1,opt,name=ack_sequence,json=ackSequence,proto3" json:"ack_sequence,omitempty"`
	HostAction        string                 `protobuf:"bytes,2,opt,name=host_action,json=hostAction,proto3" json:"host_action,omitempty"`
	TargetBitrateKbps int32                  `protobuf:"varint,3,opt,name=target_bitrate_kbps,json=targetBitrateKbps,proto3" json:"target_bitrate_kbps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_streaming_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{25}
}

func (x *TelemetryAck) GetAckSequence() int64 {
	if x != nil {
		return x.AckSequence
	}
	return 0
}

func (x *TelemetryAck) GetHostAction() string {
	if x != nil {
		return x.HostAction
	}
	return ""
}

func (x *TelemetryAck) GetTargetBitrateKbps() int32 {
	if x != nil {
		return x.TargetBitrateKbps
	}
	return 0
}

type StreamQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamQualityRequest) Reset() {
	*x = StreamQualityRequest{}
	mi := &file_streaming_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamQualityRequest) ProtoMessage() {}

func (x *StreamQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamQualityRequest.ProtoReflect.Descriptor instead.
func (*StreamQualityRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{26}
}

func (x *StreamQualityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamQualityRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type QualityUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateType    string                 `protobuf:"bytes,1,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityUpdate) Reset() {
	*x = QualityUpdate{}
	mi := &file_streaming_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityUpdate) ProtoMessage() {}

func (x *QualityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityUpdate.ProtoReflect.Descriptor instead.
func (*QualityUpdate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{27}
}

func (x *QualityUpdate) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *QualityUpdate) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *QualityUpdate) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_streaming_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{28}
}

func (x *HealthRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Checks        []*HealthCheck         `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_streaming_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{29}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetChecks() []*HealthCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_streaming_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{30}
}

func (x *HealthCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_streaming_proto protoreflect.FileDescriptor

const file_streaming_proto_rawDesc = "" +
	"\n" +
	"\x0fstreaming.proto\x12\fstreaming.v1\"\xc1\x04\n" +
	"\x10NegotiateMessage\x12>\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x19.streaming.v1.ClientHelloH\x00R\vclientHello\x12P\n" +
	"\x12host_advertisement\x18\x02 \x01(\v2\x1f.streaming.v1.HostAdvertisementH\x00R\x11hostAdvertisement\x12>\n" +
	"\fclient_offer\x18\x03 \x01(\v2\x19.streaming.v1.ClientOfferH\x00R\vclientOffer\x12;\n" +
	"\vhost_answer\x18\x04 \x01(\v2\x18.streaming.v1.HostAnswerH\x00R\n" +
	"hostAnswer\x12A\n" +
	"\rice_candidate\x18\x05 \x01(\v2\x1a.streaming.v1.ICECandidateH\x00R\ficeCandidate\x12+\n" +
	"\x05ready\x18\x06 \x01(\v2\x13.streaming.v1.ReadyH\x00R\x05ready\x12=\n" +
	"\vrenegotiate\x18\a \x01(\v2\x19.streaming.v1.RenegotiateH\x00R\vrenegotiate\x127\n" +
	"\tterminate\x18\b \x01(\v2\x17.streaming.v1.TerminateH\x00R\tterminate\x12+\n" +
	"\x05error\x18\t \x01(\v2\x13.streaming.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\xb9\x01\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\x12*\n" +
	"\x11requested_game_id\x18\x05 \x01(\tR\x0frequestedGameId\"\xdb\x02\n" +
	"\x11HostAdvertisement\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x127\n" +
	"\vgpu_entries\x18\x02 \x03(\v2\x16.streaming.v1.GPUEntryR\n" +
	"gpuEntries\x12\x16\n" +
	"\x06codecs\x18\x03 \x03(\tR\x06codecs\x12\x1e\n" +
	"\n" +
	"transports\x18\x04 \x03(\tR\n" +
	"transports\x12?\n" +
	"\x0emax_resolution\x18\x05 \x01(\v2\x18.streaming.v1.ResolutionR\rmaxResolution\x12(\n" +
	"\x10max_refresh_rate\x18\x06 \x01(\x05R\x0emaxRefreshRate\x12\x1f\n" +
	"\vhdr_formats\x18\a \x03(\tR\n" +
	"hdrFormats\x120\n" +
	"\x14thermal_headroom_pct\x18\b \x01(\x05R\x12thermalHeadroomPct\"\x99\x01\n" +
	"\bGPUEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x18\n" +
	"\aencoder\x18\x04 \x01(\tR\aencoder\x12\x16\n" +
	"\x06codecs\x18\x05 \x03(\tR\x06codecs\x12\x17\n" +
	"\avram_gb\x18\x06 \x01(\x05R\x06vramGb\"\xc9\x03\n" +
	"\vClientOffer\x12'\n" +
	"\x0fpreferred_codec\x18\x01 \x01(\tR\x0epreferredCodec\x12'\n" +
	"\x0ffallback_codecs\x18\x02 \x03(\tR\x0efallbackCodecs\x12/\n" +
	"\x13preferred_transport\x18\x03 \x01(\tR\x12preferredTransport\x12<\n" +
	"\fdisplay_caps\x18\x04 \x01(\v2\x19.streaming.v1.DisplayCapsR\vdisplayCaps\x12<\n" +
	"\fdecoder_caps\x18\x05 \x01(\v2\x19.streaming.v1.DecoderCapsR\vdecoderCaps\x12<\n" +
	"\fnetwork_caps\x18\x06 \x01(\v2\x19.streaming.v1.NetworkCapsR\vnetworkCaps\x126\n" +
	"\n" +
	"audio_caps\x18\a \x01(\v2\x17.streaming.v1.AudioCapsR\taudioCaps\x12E\n" +
	"\x0fcontroller_caps\x18\b \x01(\v2\x1c.streaming.v1.ControllerCapsR\x0econtrollerCaps\"\xee\x03\n" +
	"\n" +
	"HostAnswer\x12%\n" +
	"\x0eselected_codec\x18\x01 \x01(\tR\rselectedCodec\x12-\n" +
	"\x12selected_transport\x18\x02 \x01(\tR\x11selectedTransport\x12,\n" +
	"\x12selected_gpu_index\x18\x03 \x01(\x05R\x10selectedGpuIndex\x128\n" +
	"\n" +
	"resolution\x18\x04 \x01(\v2\x18.streaming.v1.ResolutionR\n" +
	"resolution\x12!\n" +
	"\frefresh_rate\x18\x05 \x01(\x05R\vrefreshRate\x12.\n" +
	"\x13bitrate_target_kbps\x18\x06 \x01(\x05R\x11bitrateTargetKbps\x12\x19\n" +
	"\bhdr_mode\x18\a \x01(\tR\ahdrMode\x12A\n" +
	"\x0fsrtp_parameters\x18\b \x01(\v2\x18.streaming.v1.SRTPParamsR\x0esrtpParameters\x129\n" +
	"\vquic_config\x18\t \x01(\v2\x18.streaming.v1.QUICConfigR\n" +
	"quicConfig\x126\n" +
	"\n" +
	"udp_config\x18\n" +
	" \x01(\v2\x17.streaming.v1.UDPConfigR\tudpConfig\"m\n" +
	"\fICECandidate\x12\x17\n" +
	"\asdp_mid\x18\x01 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x02 \x01(\x05R\rsdpMlineIndex\x12\x1c\n" +
	"\tcandidate\x18\x03 \x01(\tR\tcandidate\"]\n" +
	"\x05Ready\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04ssrc\x18\x02 \x01(\x05R\x04ssrc\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\x05R\vpayloadType\"]\n" +
	"\vRenegotiate\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x126\n" +
	"\tnew_offer\x18\x02 \x01(\v2\x19.streaming.v1.ClientOfferR\bnewOffer\"#\n" +
	"\tTerminate\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\n" +
	"Resolution\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"\x7f\n" +
	"\vDisplayCaps\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"refresh_hz\x18\x03 \x01(\x05R\trefreshHz\x12#\n" +
	"\rhdr_supported\x18\x04 \x01(\bR\fhdrSupported\"\x8d\x02\n" +
	"\vDecoderCaps\x12+\n" +
	"\x11hardware_decoders\x18\x01 \x03(\tR\x10hardwareDecoders\x12m\n" +
	"\x18max_resolution_per_codec\x18\x02 \x03(\v24.streaming.v1.DecoderCaps.MaxResolutionPerCodecEntryR\x15maxResolutionPerCodec\x1ab\n" +
	"\x1aMaxResolutionPerCodecEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.streaming.v1.ResolutionR\x05value:\x028\x01\"\x86\x01\n" +
	"\vNetworkCaps\x12,\n" +
	"\x12max_bandwidth_mbps\x18\x01 \x01(\x05R\x10maxBandwidthMbps\x12!\n" +
	"\fsupports_bbr\x18\x02 \x01(\bR\vsupportsBbr\x12&\n" +
	"\x0frtt_ms_estimate\x18\x03 \x01(\x05R\rrttMsEstimate\"|\n" +
	"\tAudioCaps\x12\x16\n" +
	"\x06codecs\x18\x01 \x03(\tR\x06codecs\x12!\n" +
	"\fmax_channels\x18\x02 \x01(\x05R\vmaxChannels\x124\n" +
	"\x16preferred_bitrate_kbps\x18\x03 \x01(\x05R\x14preferredBitrateKbps\"\x8b\x01\n" +
	"\x0eControllerCaps\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x16\n" +
	"\x06haptic\x18\x02 \x01(\bR\x06haptic\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\bR\atrigger\x12\x12\n" +
	"\x04gyro\x18\x04 \x01(\bR\x04gyro\x12\x1d\n" +
	"\n" +
	"audio_jack\x18\x05 \x01(\bR\taudioJack\"2\n" +
	"\n" +
	"SRTPParams\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\"F\n" +
	"\n" +
	"QUICConfig\x12\x12\n" +
	"\x04alpn\x18\x01 \x01(\tR\x04alpn\x12$\n" +
	"\x0ezero_rtt_token\x18\x02 \x01(\fR\fzeroRttToken\"J\n" +
	"\tUDPConfig\x12)\n" +
	"\x10dtls_fingerprint\x18\x01 \x01(\tR\x0fdtlsFingerprint\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xaf\x02\n" +
	"\x0fTelemetryPacket\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x122\n" +
	"\x05video\x18\x03 \x01(\v2\x1c.streaming.v1.VideoTelemetryR\x05video\x128\n" +
	"\anetwork\x18\x04 \x01(\v2\x1e.streaming.v1.NetworkTelemetryR\anetwork\x122\n" +
	"\x05input\x18\x05 \x01(\v2\x1c.streaming.v1.InputTelemetryR\x05input\x128\n" +
	"\adisplay\x18\x06 \x01(\v2\x1e.streaming.v1.DisplayTelemetryR\adisplay\"\xad\x01\n" +
	"\x0eVideoTelemetry\x12'\n" +
	"\x0fframes_received\x18\x01 \x01(\x05R\x0eframesReceived\x12%\n" +
	"\x0eframes_decoded\x18\x02 \x01(\x05R\rframesDecoded\x12%\n" +
	"\x0eframes_dropped\x18\x03 \x01(\x05R\rframesDropped\x12$\n" +
	"\x0edecode_time_ms\x18\x04 \x01(\x02R\fdecodeTimeMs\"\xcd\x01\n" +
	"\x10NetworkTelemetry\x126\n" +
	"\x17bandwidth_estimate_mbps\x18\x01 \x01(\x02R\x15bandwidthEstimateMbps\x12\x15\n" +
	"\x06rtt_ms\x18\x02 \x01(\x02R\x05rttMs\x12\x1b\n" +
	"\tjitter_ms\x18\x03 \x01(\x02R\bjitterMs\x12&\n" +
	"\x0fpacket_loss_pct\x18\x04 \x01(\x02R\rpacketLossPct\x12%\n" +
	"\x0efec_recoveries\x18\x05 \x01(\x05R\rfecRecoveries\"c\n" +
	"\x0eInputTelemetry\x12+\n" +
	"\x11controller_events\x18\x01 \x01(\x05R\x10controllerEvents\x12$\n" +
	"\x0elatency_us_avg\x18\x02 \x01(\x02R\flatencyUsAvg\"\x87\x01\n" +
	"\x10DisplayTelemetry\x12\x1b\n" +
	"\tactual_hz\x18\x01 \x01(\x02R\bactualHz\x12&\n" +
	"\x0fvsync_offset_ms\x18\x02 \x01(\x02R\rvsyncOffsetMs\x12.\n" +
	"\x13display_queue_depth\x18\x03 \x01(\x05R\x11displayQueueDepth\"\x82\x01\n" +
	"\fTelemetryAck\x12!\n" +
	"\fack_sequence\x18\x01 \x01(\x03R\vackSequence\x12\x1f\n" +
	"\vhost_action\x18\x02 \x01(\tR\n" +
	"hostAction\x12.\n" +
	"\x13target_bitrate_kbps\x18\x03 \x01(\x05R\x11targetBitrateKbps\"R\n" +
	"\x14StreamQualityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xd3\x01\n" +
	"\rQualityUpdate\x12\x1f\n" +
	"\vupdate_type\x18\x01 \x01(\tR\n" +
	"updateType\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12B\n" +
	"\adetails\x18\x03 \x03(\v2(.streaming.v1.QualityUpdate.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\rHealthRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\"[\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x121\n" +
	"\x06checks\x18\x02 \x03(\v2\x19.streaming.v1.HealthCheckR\x06checks\"Q\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail2\xd7\x02\n" +
	"\x10StreamingControl\x12U\n" +
	"\x0fNegotiateStream\x12\x1e.streaming.v1.NegotiateMessage\x1a\x1e.streaming.v1.NegotiateMessage(\x010\x01\x12L\n" +
	"\rPushTelemetry\x12\x1d.streaming.v1.TelemetryPacket\x1a\x1a.streaming.v1.TelemetryAck(\x01\x12Y\n" +
	"\x14StreamQualityUpdates\x12\".streaming.v1.StreamQualityRequest\x1a\x1b.streaming.v1.QualityUpdate0\x01\x12C\n" +
	"\x06Health\x12\x1b.streaming.v1.HealthRequest\x1a\x1c.streaming.v1.HealthResponseBCZAgithub.com/HelixDevelopment/HelixPlay/pkg/protocol/v1;streamingv1b\x06proto3"

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData []byte
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)))
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_streaming_proto_goTypes = []any{
	(*NegotiateMessage)(nil),     // 0: streaming.v1.NegotiateMessage
	(*ClientHello)(nil),          // 1: streaming.v1.ClientHello
	(*HostAdvertisement)(nil),    // 2: streaming.v1.HostAdvertisement
	(*GPUEntry)(nil),             // 3: streaming.v1.GPUEntry
	(*ClientOffer)(nil),          // 4: streaming.v1.ClientOffer
	(*HostAnswer)(nil),           // 5: streaming.v1.HostAnswer
	(*ICECandidate)(nil),         // 6: streaming.v1.ICECandidate
	(*Ready)(nil),                // 7: streaming.v1.Ready
	(*Renegotiate)(nil),          // 8: streaming.v1.Renegotiate
	(*Terminate)(nil),            // 9: streaming.v1.Terminate
	(*Error)(nil),                // 10: streaming.v1.Error
	(*Resolution)(nil),           // 11: streaming.v1.Resolution
	(*DisplayCaps)(nil),          // 12: streaming.v1.DisplayCaps
	(*DecoderCaps)(nil),          // 13: streaming.v1.DecoderCaps
	(*NetworkCaps)(nil),          // 14: streaming.v1.NetworkCaps
	(*AudioCaps)(nil),            // 15: streaming.v1.AudioCaps
	(*ControllerCaps)(nil),       // 16: streaming.v1.ControllerCaps
	(*SRTPParams)(nil),           // 17: streaming.v1.SRTPParams
	(*QUICConfig)(nil),           // 18: streaming.v1.QUICConfig
	(*UDPConfig)(nil),            // 19: streaming.v1.UDPConfig
	(*TelemetryPacket)(nil),      // 20: streaming.v1.TelemetryPacket
	(*VideoTelemetry)(nil),       // 21: streaming.v1.VideoTelemetry
	(*NetworkTelemetry)(nil),     // 22: streaming.v1.NetworkTelemetry
	(*InputTelemetry)(nil),       // 23: streaming.v1.InputTelemetry
	(*DisplayTelemetry)(nil),     // 24: streaming.v1.DisplayTelemetry
	(*TelemetryAck)(nil),         // 25: streaming.v1.TelemetryAck
	(*StreamQualityRequest)(nil), // 26: streaming.v1.StreamQualityRequest
	(*QualityUpdate)(nil),        // 27: streaming.v1.QualityUpdate
	(*HealthRequest)(nil),        // 28: streaming.v1.HealthRequest
	(*HealthResponse)(nil),       // 29: streaming.v1.HealthResponse
	(*HealthCheck)(nil),          // 30: streaming.v1.HealthCheck
	nil,                          // 31: streaming.v1.DecoderCaps.MaxResolutionPerCodecEntry
	nil,                          // 32: streaming.v1.QualityUpdate.DetailsEntry
}
var file_streaming_proto_depIdxs = []int32{
	1,  // 0: streaming.v1.NegotiateMessage.client_hello:type_name -> streaming.v1.ClientHello
	2,  // 1: streaming.v1.NegotiateMessage.host_advertisement:type_name -> streaming.v1.HostAdvertisement
	4,  // 2: streaming.v1.NegotiateMessage.client_offer:type_name -> streaming.v1.ClientOffer
	5,  // 3: streaming.v1.NegotiateMessage.host_answer:type_name -> streaming.v1.HostAnswer
	6,  // 4: streaming.v1.NegotiateMessage.ice_candidate:type_name -> streaming.v1.ICECandidate
	7,  // 5: streaming.v1.NegotiateMessage.ready:type_name -> streaming.v1.Ready
	8,  // 6: streaming.v1.NegotiateMessage.renegotiate:type_name -> streaming.v1.Renegotiate
	9,  // 7: streaming.v1.NegotiateMessage.terminate:type_name -> streaming.v1.Terminate
	10, // 8: streaming.v1.NegotiateMessage.error:type_name -> streaming.v1.Error
	3,  // 9: streaming.v1.HostAdvertisement.gpu_entries:type_name -> streaming.v1.GPUEntry
	11, // 10: streaming.v1.HostAdvertisement.max_resolution:type_name -> streaming.v1.Resolution
	12, // 11: streaming.v1.ClientOffer.display_caps:type_name -> streaming.v1.DisplayCaps
	13, // 12: streaming.v1.ClientOffer.decoder_caps:type_name -> streaming.v1.DecoderCaps
	14, // 13: streaming.v1.ClientOffer.network_caps:type_name -> streaming.v1.NetworkCaps
	15, // 14: streaming.v1.ClientOffer.audio_caps:type_name -> streaming.v1.AudioCaps
	16, // 15: streaming.v1.ClientOffer.controller_caps:type_name -> streaming.v1.ControllerCaps
	11, // 16: streaming.v1.HostAnswer.resolution:type_name -> streaming.v1.Resolution
	17, // 17: streaming.v1.HostAnswer.srtp_parameters:type_name -> streaming.v1.SRTPParams
	18, // 18: streaming.v1.HostAnswer.quic_config:type_name -> streaming.v1.QUICConfig
	19, // 19: streaming.v1.HostAnswer.udp_config:type_name -> streaming.v1.UDPConfig
	4,  // 20: streaming.v1.Renegotiate.new_offer:type_name -> streaming.v1.ClientOffer
	31, // 21: streaming.v1.DecoderCaps.max_resolution_per_codec:type_name -> streaming.v1.DecoderCaps.MaxResolutionPerCodecEntry
	21, // 22: streaming.v1.TelemetryPacket.video:type_name -> streaming.v1.VideoTelemetry
	22, // 23: streaming.v1.TelemetryPacket.network:type_name -> streaming.v1.NetworkTelemetry
	23, // 24: streaming.v1.TelemetryPacket.input:type_name -> streaming.v1.InputTelemetry
	24, // 25: streaming.v1.TelemetryPacket.display:type_name -> streaming.v1.DisplayTelemetry
	32, // 26: streaming.v1.QualityUpdate.details:type_name -> streaming.v1.QualityUpdate.DetailsEntry
	30, // 27: streaming.v1.HealthResponse.checks:type_name -> streaming.v1.HealthCheck
	11, // 28: streaming.v1.DecoderCaps.MaxResolutionPerCodecEntry.value:type_name -> streaming.v1.Resolution
	0,  // 29: streaming.v1.StreamingControl.NegotiateStream:input_type -> streaming.v1.NegotiateMessage
	20, // 30: streaming.v1.StreamingControl.PushTelemetry:input_type -> streaming.v1.TelemetryPacket
	26, // 31: streaming.v1.StreamingControl.StreamQualityUpdates:input_type -> streaming.v1.StreamQualityRequest
	28, // 32: streaming.v1.StreamingControl.Health:input_type -> streaming.v1.HealthRequest
	0,  // 33: streaming.v1.StreamingControl.NegotiateStream:output_type -> streaming.v1.NegotiateMessage
	25, // 34: streaming.v1.StreamingControl.PushTelemetry:output_type -> streaming.v1.TelemetryAck
	27, // 35: streaming.v1.StreamingControl.StreamQualityUpdates:output_type -> streaming.v1.QualityUpdate
	29, // 36: streaming.v1.StreamingControl.Health:output_type -> streaming.v1.HealthResponse
	33, // [33:37] is the sub-list for method output_type
	29, // [29:33] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	file_streaming_proto_msgTypes[0].OneofWrappers = []any{
		(*NegotiateMessage_ClientHello)(nil),
		(*NegotiateMessage_HostAdvertisement)(nil),
		(*NegotiateMessage_ClientOffer)(nil),
		(*NegotiateMessage_HostAnswer)(nil),
		(*NegotiateMessage_IceCandidate)(nil),
		(*NegotiateMessage_Ready)(nil),
		(*NegotiateMessage_Renegotiate)(nil),
		(*NegotiateMessage_Terminate)(nil),
		(*NegotiateMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
